import { CustomFieldTemplate } from '@/types/customFields';

export const CUSTOM_FIELD_TEMPLATES: CustomFieldTemplate[] = [
  // Demographics
  {
    name: 'race',
    label: 'Race',
    fieldType: 'dropdown',
    description: 'Participant race (HMIS standard)',
    required: false,
    hmisCompliant: true,
    category: 'demographics',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'American Indian, Alaska Native, or Indigenous',
      'Asian or Asian American',
      'Black, African American, or African',
      'Native Hawaiian or Pacific Islander',
      'White',
      'Client prefers not to answer',
      'Data not collected',
    ],
  },
  {
    name: 'ethnicity',
    label: 'Ethnicity',
    fieldType: 'dropdown',
    description: 'Participant ethnicity (HMIS standard)',
    required: false,
    hmisCompliant: true,
    category: 'demographics',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Hispanic/Latina/e/o',
      'Non-Hispanic/Non-Latina/e/o',
      'Client prefers not to answer',
      'Data not collected',
    ],
  },
  {
    name: 'veteran_status',
    label: 'Veteran Status',
    fieldType: 'dropdown',
    description: 'U.S. military veteran status (HMIS standard)',
    required: false,
    hmisCompliant: true,
    category: 'demographics',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Yes',
      'No',
      'Client doesn\'t know',
      'Client prefers not to answer',
      'Data not collected',
    ],
  },
  {
    name: 'disabilities',
    label: 'Disabilities',
    fieldType: 'multi-select',
    description: 'Physical or mental impairments (HMIS standard)',
    required: false,
    hmisCompliant: true,
    category: 'health',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Mental health disorder',
      'Alcohol use disorder',
      'Drug use disorder',
      'Both alcohol and drug use disorders',
      'Chronic health condition',
      'HIV/AIDS',
      'Developmental disability',
      'Physical disability',
    ],
  },
  {
    name: 'household_type',
    label: 'Household Type',
    fieldType: 'dropdown',
    description: 'Type of household (HMIS standard)',
    required: false,
    hmisCompliant: true,
    category: 'demographics',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Household without children',
      'Household with at least one adult and one child',
      'Household with only children',
    ],
  },

  // Contact Information
  {
    name: 'emergency_contact_name',
    label: 'Emergency Contact Name',
    fieldType: 'text',
    description: 'Full name of emergency contact person',
    required: false,
    hmisCompliant: false,
    category: 'contact',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    validation: {
      min: 2,
      max: 100,
      message: 'Please enter a valid name',
    },
  },
  {
    name: 'emergency_contact_phone',
    label: 'Emergency Contact Phone',
    fieldType: 'phone',
    description: 'Emergency contact phone number',
    required: false,
    hmisCompliant: false,
    category: 'contact',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
  },
  {
    name: 'emergency_contact_relationship',
    label: 'Emergency Contact Relationship',
    fieldType: 'dropdown',
    description: 'Relationship to emergency contact',
    required: false,
    hmisCompliant: false,
    category: 'contact',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Spouse/Partner',
      'Parent',
      'Child',
      'Sibling',
      'Other family member',
      'Friend',
      'Social worker',
      'Other',
    ],
  },
  {
    name: 'preferred_language',
    label: 'Preferred Language',
    fieldType: 'dropdown',
    description: 'Primary language for communication',
    required: false,
    hmisCompliant: false,
    category: 'demographics',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'English',
      'Spanish',
      'Chinese (Mandarin)',
      'Chinese (Cantonese)',
      'Vietnamese',
      'Korean',
      'Arabic',
      'Russian',
      'French',
      'Haitian Creole',
      'Portuguese',
      'Other',
    ],
  },

  // Income & Employment
  {
    name: 'monthly_income',
    label: 'Monthly Income',
    fieldType: 'number',
    description: 'Total monthly household income',
    required: false,
    hmisCompliant: false,
    category: 'income',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    helpText: 'Enter amount in dollars',
    validation: {
      min: 0,
      max: 999999,
      message: 'Please enter a valid income amount',
    },
  },
  {
    name: 'income_sources',
    label: 'Income Sources',
    fieldType: 'multi-select',
    description: 'Sources of household income',
    required: false,
    hmisCompliant: false,
    category: 'income',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Employment',
      'Unemployment benefits',
      'SSI',
      'SSDI',
      'Child support',
      'TANF',
      'General assistance',
      'Pension',
      'Workers compensation',
      'None',
      'Other',
    ],
  },
  {
    name: 'employment_status',
    label: 'Employment Status',
    fieldType: 'dropdown',
    description: 'Current employment status',
    required: false,
    hmisCompliant: false,
    category: 'income',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Employed full-time',
      'Employed part-time',
      'Self-employed',
      'Unemployed',
      'Retired',
      'Disabled',
      'Student',
      'Other',
    ],
  },

  // Housing
  {
    name: 'living_situation',
    label: 'Current Living Situation',
    fieldType: 'dropdown',
    description: 'Where participant currently resides (HMIS standard)',
    required: false,
    hmisCompliant: true,
    category: 'housing',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Emergency shelter',
      'Transitional housing',
      'Permanent supportive housing',
      'Rental by client',
      'Owned by client',
      'Staying with family',
      'Staying with friends',
      'Hotel/motel paid by client',
      'Place not meant for habitation',
      'Safe Haven',
      'Other',
    ],
  },
  {
    name: 'length_of_homelessness',
    label: 'Length of Homelessness',
    fieldType: 'dropdown',
    description: 'Duration of current homeless episode',
    required: false,
    hmisCompliant: false,
    category: 'housing',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Less than 1 month',
      '1 to 3 months',
      '4 to 6 months',
      '7 to 12 months',
      '1 to 2 years',
      '2 to 5 years',
      'More than 5 years',
      'Not applicable',
    ],
  },
  {
    name: 'times_homeless_past_3_years',
    label: 'Times Homeless in Past 3 Years',
    fieldType: 'number',
    description: 'Number of times experiencing homelessness in past 3 years (HMIS)',
    required: false,
    hmisCompliant: true,
    category: 'housing',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    validation: {
      min: 0,
      max: 99,
      message: 'Please enter a valid number',
    },
  },
  {
    name: 'housing_barriers',
    label: 'Housing Barriers',
    fieldType: 'multi-select',
    description: 'Barriers to obtaining stable housing',
    required: false,
    hmisCompliant: false,
    category: 'housing',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Poor credit',
      'No rental history',
      'Criminal background',
      'Eviction history',
      'No income',
      'Insufficient income',
      'Pets',
      'Discrimination',
      'Lack of affordable housing',
      'Other',
    ],
  },

  // Health & Safety
  {
    name: 'health_insurance',
    label: 'Health Insurance Status',
    fieldType: 'dropdown',
    description: 'Type of health insurance coverage',
    required: false,
    hmisCompliant: false,
    category: 'health',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Medicaid',
      'Medicare',
      'Private insurance',
      'VA healthcare',
      'No insurance',
      'Unknown',
    ],
  },
  {
    name: 'domestic_violence_survivor',
    label: 'Domestic Violence Survivor',
    fieldType: 'dropdown',
    description: 'Has experienced domestic/intimate partner violence (HMIS)',
    required: false,
    hmisCompliant: true,
    category: 'health',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Yes (currently fleeing)',
      'Yes (not currently fleeing)',
      'No',
      'Client doesn\'t know',
      'Client prefers not to answer',
      'Data not collected',
    ],
  },

  // Identification
  {
    name: 'ssn',
    label: 'Social Security Number',
    fieldType: 'ssn',
    description: 'Full 9-digit SSN',
    required: false,
    hmisCompliant: true,
    category: 'demographics',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    helpText: 'Encrypted and securely stored',
    validation: {
      pattern: '^\\d{9}$',
      message: 'SSN must be 9 digits',
    },
  },
  {
    name: 'drivers_license',
    label: 'Driver\'s License Number',
    fieldType: 'text',
    description: 'State-issued driver\'s license number',
    required: false,
    hmisCompliant: false,
    category: 'demographics',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
  },
  {
    name: 'birth_certificate',
    label: 'Has Birth Certificate',
    fieldType: 'checkbox',
    description: 'Participant has a birth certificate on hand',
    required: false,
    hmisCompliant: false,
    category: 'demographics',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
  },

  // Program-Specific
  {
    name: 'criminal_background',
    label: 'Criminal Background',
    fieldType: 'dropdown',
    description: 'Criminal history disclosure',
    required: false,
    hmisCompliant: false,
    category: 'other',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'No criminal history',
      'Misdemeanor(s)',
      'Felony(ies)',
      'Prefer not to answer',
    ],
  },
  {
    name: 'education_level',
    label: 'Education Level',
    fieldType: 'dropdown',
    description: 'Highest level of education completed',
    required: false,
    hmisCompliant: false,
    category: 'demographics',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Less than high school',
      'High school diploma/GED',
      'Some college',
      'Associate degree',
      'Bachelor\'s degree',
      'Graduate degree',
      'Prefer not to answer',
    ],
  },
  {
    name: 'transportation',
    label: 'Transportation',
    fieldType: 'multi-select',
    description: 'Available transportation methods',
    required: false,
    hmisCompliant: false,
    category: 'other',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    options: [
      'Personal vehicle',
      'Public transportation',
      'Bicycle',
      'Walking',
      'Family/friends',
      'None',
    ],
  },
  {
    name: 'prior_living_situation_notes',
    label: 'Prior Living Situation Notes',
    fieldType: 'textarea',
    description: 'Additional notes about housing history',
    required: false,
    hmisCompliant: false,
    category: 'housing',
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    helpText: 'Detailed description of previous housing situations',
  },
];

export function getCategoryTemplates(category: string): CustomFieldTemplate[] {
  return CUSTOM_FIELD_TEMPLATES.filter((t) => t.category === category);
}

export function getHMISTemplates(): CustomFieldTemplate[] {
  return CUSTOM_FIELD_TEMPLATES.filter((t) => t.hmisCompliant);
}

export function getTemplateByName(name: string): CustomFieldTemplate | undefined {
  return CUSTOM_FIELD_TEMPLATES.find((t) => t.name === name);
}
