import {
  Participant,
  EnrolledParticipant,
  Program,
  Site,
  Enrollment,
  ServiceReceived,
  Touchpoint,
  TouchpointExtraction,
} from '@/types/poc';
import { CustomField } from '@/types/customFields';
import { Assessment, AssessmentTemplate, Goal } from '@/types/assessments';

// Re-export service data from separate file
export { mockServiceTypes, mockServiceTransactions } from './mockServiceData';

export const mockParticipants: Participant[] = [
  {
    id: 'P-001',
    firstName: 'John',
    lastName: 'Smith',
    dateOfBirth: new Date('1985-03-15'),
    dobDataQuality: 1,
    gender: 1, // Man
    phoneNumber: '(555) 123-4567',
    email: 'john.smith@example.com',
    customData: {},
    createdAt: new Date('2026-01-15'),
    lastSeenAt: new Date('2026-03-29'),
  },
  {
    id: 'P-002',
    firstName: 'Jane',
    lastName: 'Doe',
    dateOfBirth: new Date('1990-07-22'),
    dobDataQuality: 1,
    gender: 0, // Woman
    phoneNumber: '(555) 987-6543',
    customData: {},
    createdAt: new Date('2026-02-01'),
    lastSeenAt: new Date('2026-03-20'),
  },
  {
    id: 'P-003',
    firstName: 'Michael',
    lastName: 'Johnson',
    dateOfBirth: new Date('1978-11-30'),
    dobDataQuality: 2, // Approximate
    approximateAge: 47,
    gender: 1,
    customData: {},
    createdAt: new Date('2026-01-20'),
    lastSeenAt: new Date('2026-03-25'),
  },
  {
    id: 'P-004',
    firstName: 'Maria',
    lastName: 'Garcia',
    dateOfBirth: new Date('1992-05-18'),
    dobDataQuality: 1,
    gender: 0,
    phoneNumber: '(555) 456-7890',
    email: 'maria.garcia@example.com',
    customData: {},
    createdAt: new Date('2026-02-10'),
    lastSeenAt: new Date('2026-03-28'),
  },
  {
    id: 'P-005',
    firstName: 'John',
    lastName: 'Smith',
    dateOfBirth: new Date('1990-06-10'),
    dobDataQuality: 1,
    gender: 1,
    customData: {},
    createdAt: new Date('2026-03-01'),
    lastSeenAt: new Date('2026-03-15'),
  },
];

export const mockEnrolledParticipants: EnrolledParticipant[] = [
  {
    id: 'P-001',
    firstName: 'John',
    lastName: 'Smith',
    dateOfBirth: new Date('1985-03-15'),
    gender: 1,
    program: 'Rapid Rehousing',
    enrollmentDate: new Date('2026-01-15'),
    caseWorker: 'Sarah Johnson',
    outcomeGoal: 'Secure permanent housing within 6 months',
    lastContactDate: new Date('2026-03-29'),
    phoneNumber: '(555) 123-4567',
    email: 'john.smith@example.com',
  },
  {
    id: 'P-002',
    firstName: 'Jane',
    lastName: 'Doe',
    dateOfBirth: new Date('1990-07-22'),
    gender: 0,
    program: 'Job Training',
    enrollmentDate: new Date('2026-02-01'),
    caseWorker: 'Michael Chen',
    outcomeGoal: 'Complete certification and find full-time employment',
    lastContactDate: new Date('2026-03-20'),
    phoneNumber: '(555) 987-6543',
  },
  {
    id: 'P-003',
    firstName: 'Michael',
    lastName: 'Johnson',
    dateOfBirth: new Date('1978-11-30'),
    gender: 1,
    program: 'Mental Health Services',
    enrollmentDate: new Date('2026-01-20'),
    caseWorker: 'Emily Rodriguez',
    outcomeGoal: 'Stabilize mental health and maintain independent living',
    lastContactDate: new Date('2026-03-25'),
  },
  {
    id: 'P-004',
    firstName: 'Maria',
    lastName: 'Garcia',
    dateOfBirth: new Date('1992-05-18'),
    gender: 0,
    program: 'Educational Support',
    enrollmentDate: new Date('2026-02-10'),
    caseWorker: 'Sarah Johnson',
    outcomeGoal: 'Complete GED and enroll in community college',
    lastContactDate: new Date('2026-03-28'),
    phoneNumber: '(555) 456-7890',
    email: 'maria.garcia@example.com',
  },
  {
    id: 'P-006',
    firstName: 'Robert',
    lastName: 'Williams',
    dateOfBirth: new Date('1988-09-12'),
    gender: 1,
    program: 'Emergency Shelter',
    enrollmentDate: new Date('2026-03-01'),
    caseWorker: 'David Williams',
    outcomeGoal: 'Find stable housing and employment',
    lastContactDate: new Date('2026-03-15'),
  },
];

export const mockPrograms: Program[] = [
  {
    id: 'PROG-001',
    name: 'Emergency Shelter',
    description:
      '24/7 emergency shelter providing immediate housing for individuals experiencing homelessness',
    programType: 'emergency_shelter',
    eligibilityCriteria:
      'Currently experiencing homelessness, adults 18+, no substance use on premises',
    servicesOffered: [
      'Emergency housing',
      'Meals',
      'Case management',
      'Housing navigation',
      'Basic hygiene facilities',
    ],
    enrollmentRequirements: [
      'Photo ID or other identification',
      'Intake assessment',
      'Background check',
    ],
    outcomeGoals: [
      'Secure permanent housing',
      'Employment or income source',
      'Connect to health services',
    ],
    capacity: 50,
    currentEnrollment: 42,
    status: 'active',
    requiresCaseWorker: true,
    budget: 250000, // Annual budget for emergency shelter operations
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'PROG-002',
    name: 'Rapid Rehousing',
    description:
      'Short-term rental assistance and case management to help individuals quickly exit homelessness',
    programType: 'rapid_rehousing',
    eligibilityCriteria:
      'Literally homeless or at imminent risk, income below 30% AMI, able to maintain housing with support',
    servicesOffered: [
      'Rental assistance up to 12 months',
      'Security deposits',
      'Case management',
      'Housing search assistance',
      'Financial literacy',
    ],
    enrollmentRequirements: [
      'Housing assessment',
      'Income verification',
      'Landlord references',
    ],
    outcomeGoals: [
      'Maintain stable housing for 12+ months',
      'Increase income',
      'Build savings',
    ],
    capacity: 30,
    currentEnrollment: 28,
    status: 'active',
    requiresCaseWorker: true,
    budget: 420000, // Budget for rental assistance and case management
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2026-03-15'),
  },
  {
    id: 'PROG-003',
    name: 'Job Training & Placement',
    description:
      'Comprehensive job skills training, career counseling, and employment placement services',
    programType: 'job_training',
    eligibilityCriteria:
      'Adults 18+, authorized to work in the US, committed to program completion',
    servicesOffered: [
      'Vocational training',
      'Resume writing',
      'Interview skills',
      'Job placement',
      'Work clothing',
      'Transportation assistance',
    ],
    enrollmentRequirements: ['Application', 'Interview', 'Skills assessment'],
    outcomeGoals: [
      'Complete training program',
      'Secure employment',
      'Retain job for 90+ days',
    ],
    capacity: 25,
    currentEnrollment: 19,
    status: 'active',
    requiresCaseWorker: false,
    budget: 125000, // Budget for training materials and support services
    createdAt: new Date('2025-03-10'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: 'PROG-004',
    name: 'Mental Health Support Services',
    description:
      'Comprehensive mental health counseling and support services for individuals in crisis or ongoing care',
    programType: 'mental_health_services',
    eligibilityCriteria:
      'Adults experiencing mental health challenges, referral from medical provider helpful but not required',
    servicesOffered: [
      'Individual therapy',
      'Group counseling',
      'Crisis intervention',
      'Medication management',
      'Peer support groups',
      'Family therapy',
    ],
    enrollmentRequirements: [
      'Mental health screening',
      'Release of information forms',
      'Treatment goals discussion',
    ],
    outcomeGoals: [
      'Symptom reduction',
      'Improved daily functioning',
      'Medication adherence',
      'Crisis prevention skills',
    ],
    capacity: 40,
    currentEnrollment: 35,
    status: 'active',
    requiresCaseWorker: true,
    budget: 180000, // Budget for mental health services
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2026-03-25'),
  },
  {
    id: 'PROG-005',
    name: 'Educational Support Program',
    description:
      'GED preparation, adult literacy, and continuing education support',
    programType: 'educational_support',
    eligibilityCriteria:
      'Adults 18+ seeking to complete high school education or improve literacy',
    servicesOffered: [
      'GED classes',
      'Tutoring',
      'Computer skills',
      'Study materials',
      'Test fees covered',
    ],
    enrollmentRequirements: [
      'Educational assessment',
      'Commitment letter',
      'Regular attendance',
    ],
    outcomeGoals: [
      'Pass GED exam',
      'Improve reading level',
      'Complete certification program',
    ],
    capacity: 35,
    currentEnrollment: 22,
    status: 'active',
    requiresCaseWorker: false,
    budget: 75000, // Budget for educational materials and test fees
    createdAt: new Date('2025-04-01'),
    updatedAt: new Date('2026-02-28'),
  },
  {
    id: 'PROG-006',
    name: 'Transitional Housing - Youth',
    description:
      'Transitional housing program for young adults aging out of foster care',
    programType: 'transitional_housing',
    eligibilityCriteria:
      'Ages 18-24, exited foster care, not currently enrolled in other housing program',
    servicesOffered: [
      'Housing up to 24 months',
      'Life skills training',
      'Educational support',
      'Employment services',
      'Financial coaching',
    ],
    enrollmentRequirements: [
      'Foster care verification',
      'Background check',
      'Program agreement',
    ],
    outcomeGoals: [
      'Complete education/training',
      'Secure employment',
      'Transition to permanent housing',
      'Build life skills',
    ],
    capacity: 15,
    currentEnrollment: 12,
    status: 'active',
    requiresCaseWorker: true,
    budget: 300000, // Budget for housing and comprehensive youth support
    createdAt: new Date('2025-05-15'),
    updatedAt: new Date('2026-03-01'),
  },
];

export const mockCaseWorkers = [
  { id: '1', name: 'Sarah Johnson', role: 'Case Manager' },
  { id: '2', name: 'Michael Chen', role: 'Case Manager' },
  { id: '3', name: 'Emily Rodriguez', role: 'Senior Case Manager' },
  { id: '4', name: 'David Williams', role: 'Case Manager' },
];

export const mockSites: Site[] = [
  {
    id: 'SITE-001',
    tenantId: 'TENANT-001',
    name: 'Downtown Emergency Shelter',
    address: '123 Main Street',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98101',
    phone: '(206) 555-0100',
    email: 'downtown@shelter.org',
    capacity: 50,
    active: true,
    status: 'active',
    hoursOfOperation: '24/7 - Open daily',
    accessibilityFeatures: [
      'Wheelchair accessible',
      'ADA compliant bathrooms',
      'Elevator access',
    ],
    contactPerson: 'David Williams',
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2026-03-15'),
  },
  {
    id: 'SITE-002',
    tenantId: 'TENANT-001',
    name: 'Northside Community Center',
    address: '456 Oak Avenue',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98103',
    phone: '(206) 555-0200',
    email: 'northside@community.org',
    capacity: 75,
    active: true,
    status: 'active',
    hoursOfOperation: 'Mon-Fri 8am-6pm, Sat 9am-3pm',
    accessibilityFeatures: [
      'Wheelchair accessible',
      'Accessible parking',
      'Sign language interpreters available',
    ],
    contactPerson: 'Sarah Johnson',
    createdAt: new Date('2025-02-05'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: 'SITE-003',
    name: 'Westside Health & Wellness Hub',
    address: '789 Pine Street',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98119',
    phone: '(206) 555-0300',
    email: 'wellness@westside.org',
    capacity: 40,
    programIds: ['PROG-004'], // Mental Health Services
    status: 'active',
    hoursOfOperation: 'Mon-Thu 9am-8pm, Fri 9am-5pm',
    accessibilityFeatures: [
      'Wheelchair accessible',
      'Sensory-friendly spaces',
      'Gender-neutral restrooms',
    ],
    contactPerson: 'Emily Rodriguez',
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'SITE-004',
    name: 'Hope Housing Services',
    address: '321 Elm Drive',
    city: 'Tacoma',
    state: 'WA',
    zipCode: '98402',
    phone: '(253) 555-0400',
    email: 'info@hopehousing.org',
    capacity: 30,
    programIds: ['PROG-002', 'PROG-006'], // Rapid Rehousing & Transitional Housing
    status: 'active',
    hoursOfOperation: 'Mon-Fri 9am-5pm, Emergency line 24/7',
    accessibilityFeatures: [
      'Wheelchair accessible',
      'Accessible units available',
      'Service animals welcome',
    ],
    contactPerson: 'Michael Chen',
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date('2026-03-05'),
  },
  {
    id: 'SITE-005',
    name: 'Eastside Youth Center',
    address: '555 Maple Road',
    city: 'Bellevue',
    state: 'WA',
    zipCode: '98004',
    phone: '(425) 555-0500',
    email: 'youth@eastside.org',
    capacity: 25,
    programIds: ['PROG-006'], // Transitional Housing - Youth
    status: 'active',
    hoursOfOperation: 'Mon-Fri 8am-6pm, Weekend programs vary',
    accessibilityFeatures: [
      'Wheelchair accessible',
      'Youth-friendly spaces',
      'Private counseling rooms',
    ],
    contactPerson: 'Sarah Johnson',
    createdAt: new Date('2025-04-15'),
    updatedAt: new Date('2026-02-28'),
  },
  {
    id: 'SITE-006',
    name: 'South Seattle Day Center',
    address: '888 Valley Street',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98108',
    phone: '(206) 555-0600',
    email: 'daycenter@southseattle.org',
    capacity: 60,
    programIds: ['PROG-001', 'PROG-003'], // Emergency Shelter & Job Training
    status: 'inactive',
    hoursOfOperation: 'Temporarily closed for renovations',
    accessibilityFeatures: ['Under renovation - will be fully accessible'],
    contactPerson: 'David Williams',
    createdAt: new Date('2025-06-01'),
    updatedAt: new Date('2026-01-15'),
  },
];

// Mock Enrollments - showing the proper enrollment data model
export const mockEnrollments: Enrollment[] = [
  // John Smith - Multiple enrollments showing history
  {
    id: 'ENR-001',
    tenantId: 'TENANT-001',
    enrolleeType: 'participant',
    enrolleeId: 'P-001',
    participantId: 'P-001', // Legacy - for backward compatibility
    programId: 'PROG-001', // Emergency Shelter
    siteId: 'SITE-001',
    caseWorkerId: '4', // David Williams
    startDate: new Date('2025-01-15'),
    endDate: new Date('2025-03-30'),
    status: 'completed',
    outcomes: [
      'Found permanent housing',
      'Connected to Rapid Rehousing program',
    ],
    servicesReceived: [
      {
        id: 'SVC-001',
        serviceType: 'Emergency housing',
        date: new Date('2025-01-15'),
        amount: 75,
        unit: 'nights',
        providedBy: 'Downtown Emergency Shelter',
        notes: 'Safe overnight accommodation',
      },
      {
        id: 'SVC-002',
        serviceType: 'Case management',
        date: new Date('2025-01-20'),
        amount: 15,
        unit: 'sessions',
        providedBy: 'David Williams',
        notes: 'Weekly case management meetings',
      },
      {
        id: 'SVC-003',
        serviceType: 'Meals',
        date: new Date('2025-01-15'),
        amount: 225,
        unit: 'meals',
        providedBy: 'Downtown Emergency Shelter',
        notes: '3 meals per day for 75 days',
      },
    ],
    outcomeGoals: ['Secure permanent housing', 'Employment or income source'],
    notes: 'Successfully transitioned to Rapid Rehousing after 75 days',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-03-30'),
  },
  {
    id: 'ENR-002',
    tenantId: 'TENANT-001',
    enrolleeType: 'participant',
    enrolleeId: 'P-001',
    participantId: 'P-001', // Legacy - for backward compatibility
    programId: 'PROG-003', // Job Training
    siteId: 'SITE-002',
    caseWorkerId: '1', // Sarah Johnson
    startDate: new Date('2025-02-15'),
    endDate: new Date('2025-05-20'),
    status: 'completed',
    outcomes: [
      'Completed training program',
      'Employed at local cafe',
      'Retained job for 90+ days',
    ],
    servicesReceived: [
      {
        id: 'SVC-004',
        serviceType: 'Vocational training',
        date: new Date('2025-02-15'),
        amount: 12,
        unit: 'weeks',
        providedBy: 'Northside Community Center',
        notes: 'Food service training program',
      },
      {
        id: 'SVC-005',
        serviceType: 'Job placement assistance',
        date: new Date('2025-05-01'),
        amount: 1,
        unit: 'placement',
        providedBy: 'Sarah Johnson',
        notes: 'Connected with local employer',
      },
      {
        id: 'SVC-006',
        serviceType: 'Work clothing',
        date: new Date('2025-05-15'),
        amount: 150,
        unit: 'dollars',
        providedBy: 'Northside Community Center',
        notes: 'Professional attire for new job',
      },
    ],
    outcomeGoals: [
      'Complete training program',
      'Secure employment',
      'Retain job for 90+ days',
    ],
    notes: 'Participant excelled in training and secured employment quickly',
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-05-20'),
  },
  {
    id: 'ENR-003',
    tenantId: 'TENANT-001',
    enrolleeType: 'participant',
    enrolleeId: 'P-001',
    participantId: 'P-001', // Legacy - for backward compatibility
    programId: 'PROG-002', // Rapid Rehousing - Currently active
    siteId: 'SITE-004',
    caseWorkerId: 'USER-001', // Sarah Johnson
    startDate: new Date('2025-10-01'),
    endDate: null, // Active enrollment
    status: 'active',
    outcomes: [],
    servicesReceived: [
      {
        id: 'SVC-007',
        serviceType: 'Rental assistance',
        date: new Date('2025-10-01'),
        amount: 2000,
        unit: 'dollars',
        providedBy: 'Hope Housing Services',
        notes: 'Security deposit for new apartment',
      },
      {
        id: 'SVC-008',
        serviceType: 'Rental assistance',
        date: new Date('2025-11-01'),
        amount: 1200,
        unit: 'dollars',
        providedBy: 'Hope Housing Services',
        notes: 'Monthly rent assistance - month 1',
      },
      {
        id: 'SVC-009',
        serviceType: 'Rental assistance',
        date: new Date('2025-12-01'),
        amount: 1200,
        unit: 'dollars',
        providedBy: 'Hope Housing Services',
        notes: 'Monthly rent assistance - month 2',
      },
      {
        id: 'SVC-010',
        serviceType: 'Housing counseling',
        date: new Date('2025-10-15'),
        amount: 12,
        unit: 'sessions',
        providedBy: 'Sarah Johnson',
        notes: 'Financial literacy and tenancy skills',
      },
    ],
    outcomeGoals: [
      'Maintain stable housing for 12+ months',
      'Increase income',
      'Build savings',
    ],
    notes: 'Ongoing rental assistance, participant is stable and employed',
    nextCheckIn: new Date('2026-04-16T14:00:00'), // Tomorrow at 2pm
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2026-03-29'),
  },
  // Jane Doe - Active job training + transferred from emergency shelter
  {
    id: 'ENR-004',
    tenantId: 'TENANT-001',
    enrolleeType: 'participant',
    enrolleeId: 'P-002',
    participantId: 'P-002', // Legacy - for backward compatibility
    programId: 'PROG-001', // Emergency Shelter
    siteId: 'SITE-001',
    caseWorkerId: '4', // David Williams
    startDate: new Date('2025-10-15'),
    endDate: new Date('2026-02-01'),
    status: 'transferred',
    dismissalReason:
      'Transferred to Job Training program - ready for next level of support',
    outcomes: ['Stabilized housing situation', 'Ready for job training'],
    servicesReceived: [
      {
        id: 'SVC-021',
        serviceType: 'Emergency housing',
        date: new Date('2025-10-15'),
        amount: 109,
        unit: 'nights',
        providedBy: 'Downtown Emergency Shelter',
        notes: 'Shelter stay before transfer',
      },
      {
        id: 'SVC-022',
        serviceType: 'Case management',
        date: new Date('2025-10-20'),
        amount: 16,
        unit: 'sessions',
        providedBy: 'David Williams',
        notes: 'Weekly support meetings',
      },
    ],
    outcomeGoals: ['Stabilize situation', 'Prepare for employment'],
    notes: 'Successful transition to job training program',
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'ENR-005',
    tenantId: 'TENANT-001',
    enrolleeType: 'participant',
    enrolleeId: 'P-002',
    participantId: 'P-002', // Legacy - for backward compatibility
    programId: 'PROG-003', // Job Training
    siteId: 'SITE-002',
    caseWorkerId: 'USER-002', // Michael Chen
    startDate: new Date('2026-02-01'),
    endDate: null,
    status: 'active',
    outcomes: [],
    servicesReceived: [
      {
        id: 'SVC-011',
        serviceType: 'Vocational training',
        date: new Date('2026-02-01'),
        amount: 8,
        unit: 'weeks',
        providedBy: 'Northside Community Center',
        notes: 'IT certification program - ongoing',
      },
      {
        id: 'SVC-012',
        serviceType: 'Transportation assistance',
        date: new Date('2026-02-01'),
        amount: 200,
        unit: 'dollars',
        providedBy: 'Northside Community Center',
        notes: 'Monthly bus pass',
      },
    ],
    outcomeGoals: [
      'Complete training program',
      'Secure employment',
      'Retain job for 90+ days',
    ],
    notes: 'Participant showing strong progress in IT training',
    nextCheckIn: new Date('2026-04-15T10:30:00'), // Today at 10:30am
    nextCheckInZoomLink: 'https://zoom.us/j/123456789', // Virtual check-in
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-03-20'),
  },
  // Michael Johnson - Dismissed from Emergency Shelter, now in Mental Health Services
  {
    id: 'ENR-006',
    tenantId: 'TENANT-001',
    enrolleeType: 'participant',
    enrolleeId: 'P-003',
    participantId: 'P-003', // Legacy - for backward compatibility
    programId: 'PROG-001', // Emergency Shelter
    siteId: 'SITE-001',
    caseWorkerId: '4', // David Williams
    startDate: new Date('2025-11-01'),
    endDate: new Date('2025-12-15'),
    status: 'dismissed',
    dismissalReason:
      'Repeated violations of shelter rules - substance use on premises',
    outcomes: ['Connected to substance abuse treatment program'],
    servicesReceived: [
      {
        id: 'SVC-019',
        serviceType: 'Emergency housing',
        date: new Date('2025-11-01'),
        amount: 44,
        unit: 'nights',
        providedBy: 'Downtown Emergency Shelter',
        notes: 'Shelter stay before dismissal',
      },
      {
        id: 'SVC-020',
        serviceType: 'Referral to treatment',
        date: new Date('2025-12-15'),
        amount: 1,
        unit: 'referral',
        providedBy: 'David Williams',
        notes: 'Connected to substance abuse treatment',
      },
    ],
    outcomeGoals: ['Secure permanent housing', 'Address substance use'],
    notes:
      'Participant dismissed but successfully connected to appropriate treatment services',
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-12-15'),
  },
  {
    id: 'ENR-007',
    tenantId: 'TENANT-001',
    enrolleeType: 'participant',
    enrolleeId: 'P-003',
    participantId: 'P-003', // Legacy - for backward compatibility
    programId: 'PROG-004', // Mental Health Services
    siteId: 'SITE-003',
    caseWorkerId: 'USER-003', // Emily Rodriguez
    startDate: new Date('2026-01-20'),
    endDate: null,
    status: 'active',
    outcomes: [],
    servicesReceived: [
      {
        id: 'SVC-013',
        serviceType: 'Individual therapy',
        date: new Date('2026-01-25'),
        amount: 20,
        unit: 'sessions',
        providedBy: 'Westside Health & Wellness Hub',
        notes: 'Weekly therapy sessions',
      },
      {
        id: 'SVC-014',
        serviceType: 'Group counseling',
        date: new Date('2026-02-01'),
        amount: 8,
        unit: 'sessions',
        providedBy: 'Westside Health & Wellness Hub',
        notes: 'Peer support group meetings',
      },
      {
        id: 'SVC-015',
        serviceType: 'Medication management',
        date: new Date('2026-01-20'),
        amount: 3,
        unit: 'appointments',
        providedBy: 'Westside Health & Wellness Hub',
        notes: 'Psychiatric consultations',
      },
    ],
    outcomeGoals: [
      'Symptom reduction',
      'Improved daily functioning',
      'Medication adherence',
    ],
    notes:
      'Participant showing significant improvement in mental health stability',
    nextCheckIn: new Date('2026-04-14T09:00:00'), // Yesterday at 9am (overdue)
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-03-25'),
  },
  // Maria Garcia - Educational support enrollment
  {
    id: 'ENR-008',
    tenantId: 'TENANT-001',
    enrolleeType: 'participant',
    enrolleeId: 'P-004',
    participantId: 'P-004', // Legacy - for backward compatibility
    programId: 'PROG-005', // Educational Support
    siteId: 'SITE-002',
    caseWorkerId: 'USER-001', // Sarah Johnson
    startDate: new Date('2026-02-10'),
    endDate: null,
    status: 'active',
    outcomes: [],
    servicesReceived: [
      {
        id: 'SVC-016',
        serviceType: 'GED classes',
        date: new Date('2026-02-10'),
        amount: 80,
        unit: 'hours',
        providedBy: 'Northside Community Center',
        notes: 'GED preparation course',
      },
      {
        id: 'SVC-017',
        serviceType: 'Tutoring',
        date: new Date('2026-02-15'),
        amount: 12,
        unit: 'sessions',
        providedBy: 'Northside Community Center',
        notes: 'One-on-one math tutoring',
      },
      {
        id: 'SVC-018',
        serviceType: 'Test fees',
        date: new Date('2026-03-15'),
        amount: 150,
        unit: 'dollars',
        providedBy: 'Educational Support Program',
        notes: 'GED exam fees covered',
      },
    ],
    outcomeGoals: [
      'Pass GED exam',
      'Improve reading level',
      'Enroll in community college',
    ],
    notes: 'Participant scheduled to take GED exam in April 2026',
    nextCheckIn: new Date('2026-04-22T15:30:00'), // Next week Tuesday at 3:30pm
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-03-28'),
  },

  // Example: Family-level enrollment (entire household in program)
  {
    id: 'ENR-009',
    tenantId: 'TENANT-001',
    enrolleeType: 'family',
    enrolleeId: 'HH-001',
    householdId: 'HH-001', // Legacy - for backward compatibility
    programId: 'PROG-002', // Rapid Rehousing - family-level support
    siteId: 'SITE-004',
    caseWorkerId: '1', // Sarah Johnson
    startDate: new Date('2026-01-10'),
    endDate: null,
    status: 'active',
    outcomes: [],
    servicesReceived: [
      {
        id: 'SVC-030',
        serviceType: 'Family case management',
        date: new Date('2026-01-10'),
        amount: 10,
        unit: 'sessions',
        providedBy: 'Sarah Johnson',
        notes: 'Family-level support and coordination',
      },
      {
        id: 'SVC-031',
        serviceType: 'Rental assistance',
        date: new Date('2026-01-10'),
        amount: 3500,
        unit: 'dollars',
        providedBy: 'Hope Housing Services',
        notes: 'First month rent + security deposit for family',
      },
    ],
    outcomeGoals: [
      'Maintain stable housing',
      'Increase family income',
      'Children succeed in school',
    ],
    notes:
      'Family-level enrollment provides coordinated support for entire household',
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-03-25'),
  },

  // Example: Entity enrollment (institutional partnership)
  {
    id: 'ENR-010',
    tenantId: 'TENANT-001',
    enrolleeType: 'entity',
    enrolleeId: 'ENTITY-001', // Seattle Public Schools
    programId: 'PROG-005', // Educational Support - partnership program
    siteId: 'SITE-002',
    caseWorkerId: '1', // Sarah Johnson
    startDate: new Date('2025-09-01'),
    endDate: null,
    status: 'active',
    outcomes: ['Partnership established', 'Referral pathway created'],
    servicesReceived: [
      {
        id: 'SVC-032',
        serviceType: 'Partnership coordination',
        date: new Date('2025-09-01'),
        amount: 24,
        unit: 'meetings',
        providedBy: 'Sarah Johnson',
        notes: 'Quarterly partnership meetings and coordination',
      },
      {
        id: 'SVC-033',
        serviceType: 'Training provided',
        date: new Date('2025-10-15'),
        amount: 5,
        unit: 'sessions',
        providedBy: 'Northside Community Center',
        notes: 'Staff training on referral processes',
      },
    ],
    outcomeGoals: [
      'Strengthen partnership',
      'Increase student referrals',
      'Improve educational outcomes',
    ],
    notes:
      'Institutional partnership with Seattle Public Schools for student support services',
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2026-03-20'),
  },
];

// Mock Touchpoints - realistic touchpoint patterns across enrollments
export const mockTouchpoints: Touchpoint[] = [
  // John Smith - Rapid Rehousing (ENR-003) - Weekly check-ins
  {
    id: 'TP-001',
    enrollmentId: 'ENR-003',
    participantId: 'P-001',
    caseWorkerId: '1', // Sarah Johnson
    touchpointType: 'in-person',
    content:
      'Met with John today at the Hope Housing office. He has been in his new apartment for 2 weeks now and things are going well. We discussed his budget and he showed me his work schedule - he is working 30 hours per week at the cafe making $15/hour. He paid his first month of utilities on time. We reviewed his savings goal and he has saved $200 so far. He seems hopeful and motivated. Scheduled follow-up for next Tuesday.',
    duration: 45,
    location: 'SITE-004',
    extractedData: {
      servicesProvided: [
        {
          serviceType: 'Housing counseling',
          quantity: 1,
          unit: 'session',
          confidence: 0.95,
          createTransaction: true,
        },
      ],
      progressOnGoals: [
        {
          goal: 'Maintain stable housing for 12+ months',
          status: 'positive',
          notes: 'In apartment for 2 weeks, paid utilities on time',
          percentComplete: 10,
        },
        {
          goal: 'Build savings',
          status: 'positive',
          notes: 'Has saved $200',
          percentComplete: 20,
        },
      ],
      outcomeAchievements: [],
      newNeeds: [],
      actionItems: [
        { description: 'Follow-up meeting next Tuesday', completed: false },
      ],
      emotionalState: {
        primary: 'hopeful',
        description: 'Motivated and optimistic about progress',
      },
      riskFlags: [],
      incomeChange: {
        from: 'Part-time employment',
        to: 'Steady 30 hours/week',
        date: new Date('2026-03-15'),
        description: 'Working 30 hours per week at cafe, earning $15/hour',
      },
      confidence: {
        servicesProvided: 0.95,
        progressOnGoals: 0.9,
        emotionalState: 0.85,
        incomeChange: 0.9,
      },
    },
    servicesRecorded: [],
    createdAt: new Date('2026-03-29'),
    updatedAt: new Date('2026-03-29'),
  },
  {
    id: 'TP-002',
    enrollmentId: 'ENR-003',
    participantId: 'P-001',
    caseWorkerId: '1',
    touchpointType: 'phone',
    content:
      'Quick check-in call with John. He mentioned he is having some minor issues with his upstairs neighbor making noise late at night. I advised him on how to address this with his landlord professionally. Also confirmed he received his rental assistance payment for this month. Call lasted about 15 minutes.',
    duration: 15,
    extractedData: {
      servicesProvided: [
        {
          serviceType: 'Rental assistance',
          quantity: 1,
          amount: 1200,
          unit: 'dollars',
          confidence: 0.9,
          createTransaction: false, // Already recorded separately
        },
      ],
      progressOnGoals: [
        {
          goal: 'Maintain stable housing',
          status: 'neutral',
          notes: 'Minor neighbor noise issue, manageable',
        },
      ],
      outcomeAchievements: [],
      newNeeds: ['Conflict resolution support with neighbor'],
      actionItems: [
        {
          description: 'Contact landlord about noise issue if it continues',
          completed: false,
        },
      ],
      riskFlags: [
        {
          type: 'housing',
          severity: 'low',
          description: 'Minor neighbor noise complaint',
        },
      ],
      confidence: {
        servicesProvided: 0.9,
        progressOnGoals: 0.85,
        newNeeds: 0.8,
        riskFlags: 0.75,
      },
    },
    servicesRecorded: [],
    createdAt: new Date('2026-03-22'),
    updatedAt: new Date('2026-03-22'),
  },
  // Maria Garcia - Educational Support (ENR-008) - Progress toward GED
  {
    id: 'TP-003',
    enrollmentId: 'ENR-008',
    participantId: 'P-004',
    caseWorkerId: '1',
    touchpointType: 'in-person',
    content:
      'Maria came in for her weekly check-in. She just completed her GED practice test and scored 85% - she is ready for the real exam! We scheduled her official GED test for April 15th. She is very excited and nervous. I provided her with $150 to cover the test fees. She mentioned she has been talking to the community college advisor about enrolling in their healthcare program in the fall. This is a huge milestone for her.',
    duration: 60,
    location: 'SITE-002',
    extractedData: {
      servicesProvided: [
        {
          serviceType: 'Test fees',
          quantity: 1,
          amount: 150,
          unit: 'dollars',
          confidence: 0.98,
          createTransaction: true,
        },
        {
          serviceType: 'Educational counseling',
          quantity: 1,
          unit: 'session',
          confidence: 0.95,
          createTransaction: true,
        },
      ],
      progressOnGoals: [
        {
          goal: 'Complete GED',
          status: 'positive',
          notes:
            'Scored 85% on practice test, scheduled for real exam April 15',
          percentComplete: 90,
        },
        {
          goal: 'Enroll in community college',
          status: 'positive',
          notes:
            'Talking with community college advisor about healthcare program',
          percentComplete: 30,
        },
      ],
      outcomeAchievements: [
        {
          goal: 'Ready for GED exam',
          achieved: true,
          date: new Date('2026-03-28'),
          evidence: 'Scored 85% on practice test',
          confidence: 0.95,
        },
      ],
      newNeeds: [],
      actionItems: [
        {
          description: 'Take GED exam on April 15th',
          dueDate: new Date('2026-04-15'),
          completed: false,
        },
        {
          description: 'Follow up on community college application',
          completed: false,
        },
      ],
      emotionalState: {
        primary: 'excited',
        description: 'Very excited and nervous about upcoming GED exam',
      },
      riskFlags: [],
      confidence: {
        servicesProvided: 0.98,
        progressOnGoals: 0.95,
        outcomeAchievements: 0.95,
        emotionalState: 0.9,
      },
    },
    servicesRecorded: [],
    createdAt: new Date('2026-03-28'),
    updatedAt: new Date('2026-03-28'),
  },
  // Jane Doe - Job Training (ENR-005) - Mid-program check-in
  {
    id: 'TP-004',
    enrollmentId: 'ENR-005',
    participantId: 'P-002',
    caseWorkerId: '2', // Michael Chen
    touchpointType: 'in-person',
    content:
      'Jane attended her IT training session today. She has completed 6 out of 10 modules for her certification. Instructor reports she is doing excellent work. Jane mentioned she is struggling with transportation costs - her monthly bus pass ran out and she needs help getting to class. I provided her with $200 for another monthly pass and some gas cards. We also discussed resume building and she will attend our resume workshop next week.',
    duration: 40,
    location: 'SITE-002',
    extractedData: {
      servicesProvided: [
        {
          serviceType: 'Transportation assistance',
          quantity: 1,
          amount: 200,
          unit: 'dollars',
          confidence: 0.95,
          createTransaction: true,
        },
        {
          serviceType: 'Case management',
          quantity: 1,
          unit: 'session',
          confidence: 0.9,
          createTransaction: true,
        },
      ],
      progressOnGoals: [
        {
          goal: 'Complete IT certification',
          status: 'positive',
          notes: 'Completed 6 out of 10 modules, excellent work',
          percentComplete: 60,
        },
      ],
      outcomeAchievements: [],
      newNeeds: ['Transportation assistance'],
      actionItems: [
        {
          description: 'Attend resume workshop next week',
          completed: false,
        },
      ],
      riskFlags: [
        {
          type: 'financial',
          severity: 'low',
          description: 'Struggling with transportation costs',
        },
      ],
      confidence: {
        servicesProvided: 0.95,
        progressOnGoals: 0.9,
        newNeeds: 0.85,
        riskFlags: 0.8,
      },
    },
    servicesRecorded: [],
    createdAt: new Date('2026-03-20'),
    updatedAt: new Date('2026-03-20'),
  },
  // Michael Johnson - Mental Health Services (ENR-007) - Crisis touchpoint
  {
    id: 'TP-005',
    enrollmentId: 'ENR-007',
    participantId: 'P-003',
    caseWorkerId: '3', // Emily Rodriguez
    touchpointType: 'in-person',
    content:
      'Emergency session with Michael today. He called saying he was having a crisis and thoughts of self-harm. Saw him immediately at the wellness center. We talked for 90 minutes. He has been struggling with managing his medication - he ran out 3 days ago and did not call to refill. I helped him contact the pharmacy and his psychiatrist for an emergency refill. We also developed a crisis safety plan together. He agreed to check in daily this week. Psychiatrist wants to see him tomorrow for medication management.',
    duration: 90,
    location: 'SITE-003',
    extractedData: {
      servicesProvided: [
        {
          serviceType: 'Crisis intervention',
          quantity: 1,
          unit: 'session',
          confidence: 0.98,
          createTransaction: true,
        },
        {
          serviceType: 'Medication management coordination',
          quantity: 1,
          unit: 'session',
          confidence: 0.95,
          createTransaction: true,
        },
      ],
      progressOnGoals: [
        {
          goal: 'Medication adherence',
          status: 'negative',
          notes: 'Ran out of medication 3 days ago, did not refill',
          percentComplete: 40,
        },
      ],
      outcomeAchievements: [],
      newNeeds: ['Daily check-ins this week', 'Medication adherence support'],
      actionItems: [
        {
          description: 'Daily check-ins this week',
          completed: false,
        },
        {
          description: 'Psychiatrist appointment tomorrow',
          dueDate: new Date('2026-03-26'),
          completed: false,
        },
      ],
      emotionalState: {
        primary: 'distressed',
        description: 'Crisis state with thoughts of self-harm',
      },
      riskFlags: [
        {
          type: 'safety',
          severity: 'high',
          description: 'Thoughts of self-harm, medication lapse',
        },
        {
          type: 'health',
          severity: 'high',
          description: 'Stopped taking psychiatric medication 3 days ago',
        },
      ],
      healthChange: {
        from: 'Stable on medication',
        to: 'Crisis - off medication',
        date: new Date('2026-03-25'),
        description: 'Medication lapse leading to mental health crisis',
      },
      confidence: {
        servicesProvided: 0.98,
        progressOnGoals: 0.95,
        emotionalState: 0.95,
        riskFlags: 0.98,
        healthChange: 0.95,
      },
    },
    servicesRecorded: [],
    createdAt: new Date('2026-03-25'),
    updatedAt: new Date('2026-03-25'),
  },
  // John Smith - Earlier touchpoint from emergency shelter (ENR-001)
  {
    id: 'TP-006',
    enrollmentId: 'ENR-001',
    participantId: 'P-001',
    caseWorkerId: '4', // David Williams
    touchpointType: 'in-person',
    content:
      'John completed his housing application today! We worked together on the paperwork for rapid rehousing program. He has all the required documents including pay stubs from his new job at the cafe. He will start work next week. The housing coordinator reviewed his application and approved him for the rapid rehousing program starting March 30. John is relieved and excited to have his own place.',
    duration: 75,
    location: 'SITE-001',
    extractedData: {
      servicesProvided: [
        {
          serviceType: 'Housing search assistance',
          quantity: 1,
          unit: 'session',
          confidence: 0.95,
          createTransaction: true,
        },
      ],
      progressOnGoals: [
        {
          goal: 'Secure permanent housing',
          status: 'positive',
          notes: 'Approved for rapid rehousing program starting March 30',
          percentComplete: 95,
        },
      ],
      outcomeAchievements: [
        {
          goal: 'Approved for rapid rehousing',
          achieved: true,
          date: new Date('2025-03-20'),
          evidence: 'Housing coordinator approved application',
          confidence: 0.98,
        },
      ],
      newNeeds: [],
      actionItems: [
        {
          description: 'Start work at cafe next week',
          dueDate: new Date('2025-03-27'),
          completed: true,
        },
        {
          description: 'Move into new apartment',
          dueDate: new Date('2025-03-30'),
          completed: true,
        },
      ],
      emotionalState: {
        primary: 'relieved',
        description: 'Relieved and excited to have own place',
      },
      employmentChange: {
        from: 'Unemployed',
        to: 'Employed at cafe',
        date: new Date('2025-03-20'),
        description: 'Starting job at cafe next week',
      },
      housingChange: {
        from: 'Emergency shelter',
        to: 'Approved for rapid rehousing',
        date: new Date('2025-03-20'),
        description: 'Approved for rapid rehousing program',
      },
      riskFlags: [],
      confidence: {
        servicesProvided: 0.95,
        progressOnGoals: 0.95,
        outcomeAchievements: 0.98,
        emotionalState: 0.9,
        employmentChange: 0.95,
        housingChange: 0.98,
      },
    },
    servicesRecorded: [],
    createdAt: new Date('2025-03-20'),
    updatedAt: new Date('2025-03-20'),
  },
];

export const mockCustomFields: CustomField[] = [
  {
    id: 'CF-001',
    name: 'veteran_status',
    label: 'Veteran Status',
    fieldType: 'dropdown',
    required: false,
    options: [
      'Yes',
      'No',
      "Client doesn't know",
      'Client prefers not to answer',
      'Data not collected',
    ],
    helpText: 'U.S. military veteran status',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: false,
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    hmisCompliant: true,
    order: 1,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'CF-002',
    name: 'race',
    label: 'Race',
    fieldType: 'dropdown',
    required: false,
    options: [
      'American Indian, Alaska Native, or Indigenous',
      'Asian or Asian American',
      'Black, African American, or African',
      'Native Hawaiian or Pacific Islander',
      'White',
      'Client prefers not to answer',
      'Data not collected',
    ],
    helpText: 'HMIS standard race field',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: false,
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    hmisCompliant: true,
    order: 2,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'CF-003',
    name: 'ethnicity',
    label: 'Ethnicity',
    fieldType: 'dropdown',
    required: false,
    options: [
      'Hispanic/Latina/e/o',
      'Non-Hispanic/Non-Latina/e/o',
      'Client prefers not to answer',
      'Data not collected',
    ],
    helpText: 'HMIS standard ethnicity field',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: false,
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    hmisCompliant: true,
    order: 3,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'CF-004',
    name: 'emergency_contact_name',
    label: 'Emergency Contact Name',
    fieldType: 'text',
    required: false,
    helpText: 'Full name of emergency contact person',
    validation: {
      min: 2,
      max: 100,
      message: 'Please enter a valid name',
    },
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: false,
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    hmisCompliant: false,
    order: 4,
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-05'),
  },
  {
    id: 'CF-005',
    name: 'emergency_contact_phone',
    label: 'Emergency Contact Phone',
    fieldType: 'phone',
    required: false,
    helpText: 'Emergency contact phone number',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: false,
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    hmisCompliant: false,
    order: 5,
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-05'),
  },
  {
    id: 'CF-006',
    name: 'monthly_income',
    label: 'Monthly Income',
    fieldType: 'number',
    required: false,
    helpText: 'Total monthly household income in dollars',
    validation: {
      min: 0,
      max: 999999,
      message: 'Please enter a valid income amount',
    },
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-002', 'PROG-006'],
    hmisCompliant: false,
    appliesTo: 'individual' as const,
    profiles: [],
    synonyms: [],
    order: 6,
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 'CF-007',
    name: 'disabilities',
    label: 'Disabilities',
    fieldType: 'multi-select',
    required: false,
    options: [
      'Mental health disorder',
      'Alcohol use disorder',
      'Drug use disorder',
      'Both alcohol and drug use disorders',
      'Chronic health condition',
      'HIV/AIDS',
      'Developmental disability',
      'Physical disability',
    ],
    helpText: 'Physical or mental impairments (HMIS standard)',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: false,
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    hmisCompliant: true,
    order: 7,
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'CF-008',
    name: 'living_situation',
    label: 'Current Living Situation',
    fieldType: 'dropdown',
    required: true,
    options: [
      'Emergency shelter',
      'Transitional housing',
      'Permanent supportive housing',
      'Rental by client',
      'Owned by client',
      'Staying with family',
      'Staying with friends',
      'Hotel/motel paid by client',
      'Place not meant for habitation',
      'Safe Haven',
      'Other',
    ],
    helpText: 'Where participant currently resides (HMIS standard)',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-001', 'PROG-002', 'PROG-006'],
    hmisCompliant: true,
    appliesTo: 'individual' as const,
    profiles: [],
    synonyms: [],
    order: 8,
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'CF-009',
    name: 'employment_status',
    label: 'Employment Status',
    fieldType: 'dropdown',
    required: false,
    options: [
      'Employed full-time',
      'Employed part-time',
      'Self-employed',
      'Unemployed',
      'Retired',
      'Disabled',
      'Student',
      'Other',
    ],
    helpText: 'Current employment status',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-003'],
    hmisCompliant: false,
    appliesTo: 'individual' as const,
    profiles: [],
    synonyms: [],
    order: 9,
    createdAt: new Date('2026-01-25'),
    updatedAt: new Date('2026-01-25'),
  },
  {
    id: 'CF-010',
    name: 'education_level',
    label: 'Education Level',
    fieldType: 'dropdown',
    required: false,
    options: [
      'Less than high school',
      'High school diploma/GED',
      'Some college',
      'Associate degree',
      "Bachelor's degree",
      'Graduate degree',
      'Prefer not to answer',
    ],
    helpText: 'Highest level of education completed',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-005'],
    hmisCompliant: false,
    appliesTo: 'individual' as const,
    profiles: [],
    synonyms: [],
    order: 10,
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'CF-011',
    name: 'housing_barriers',
    label: 'Housing Barriers',
    fieldType: 'multi-select',
    required: false,
    options: [
      'Poor credit',
      'No rental history',
      'Criminal background',
      'Eviction history',
      'No income',
      'Insufficient income',
      'Pets',
      'Discrimination',
      'Lack of affordable housing',
      'Other',
    ],
    helpText: 'Barriers to obtaining stable housing',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-002'],
    hmisCompliant: false,
    appliesTo: 'individual' as const,
    profiles: [],
    synonyms: [],
    order: 11,
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-02-05'),
  },
  {
    id: 'CF-012',
    name: 'prior_living_situation_notes',
    label: 'Prior Living Situation Notes',
    fieldType: 'textarea',
    required: false,
    helpText: 'Detailed description of previous housing situations',
    visibleInIntake: false,
    visibleInProfile: true,
    programSpecific: false,
    appliesTo: 'individual',
    profiles: [],
    synonyms: [],
    hmisCompliant: false,
    order: 12,
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'CF-013',
    name: 'disabilities',
    label: 'Disabilities',
    fieldType: 'multi-select',
    required: false,
    options: [
      'Physical disability',
      'Developmental disability',
      'Chronic health condition',
      'HIV/AIDS',
      'Mental health disorder',
      'Substance use disorder',
      'No',
      'Client prefers not to answer',
      'Data not collected',
    ],
    helpText: 'HMIS standard disability types (select all that apply)',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: false,
    appliesTo: 'individual' as const,
    profiles: ['hmis' as const],
    synonyms: [],
    hmisCompliant: true,
    order: 13,
    createdAt: new Date('2026-02-15'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'CF-014',
    name: 'mental_health_diagnosis',
    label: 'Mental Health Diagnosis',
    fieldType: 'multi-select',
    required: false,
    options: [
      'Depression',
      'Anxiety disorder',
      'Bipolar disorder',
      'PTSD',
      'Schizophrenia',
      'Personality disorder',
      'Eating disorder',
      'ADHD',
      'Other diagnosis',
      'Client prefers not to answer',
    ],
    helpText: 'Current mental health diagnoses (select all that apply)',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-004'],
    appliesTo: 'individual' as const,
    profiles: [],
    synonyms: [],
    hmisCompliant: false,
    order: 14,
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'CF-015',
    name: 'substance_use_history',
    label: 'Substance Use History',
    fieldType: 'dropdown',
    required: false,
    options: [
      'No history',
      'Former use - in recovery',
      'Current use - seeking treatment',
      'Current use - not seeking treatment',
      'Client prefers not to answer',
      'Data not collected',
    ],
    helpText: 'History of substance use (HMIS standard)',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-001', 'PROG-004'],
    appliesTo: 'individual' as const,
    profiles: ['hmis' as const],
    synonyms: [],
    hmisCompliant: true,
    order: 15,
    createdAt: new Date('2026-02-25'),
    updatedAt: new Date('2026-02-25'),
  },
  {
    id: 'CF-016',
    name: 'criminal_justice_involvement',
    label: 'Criminal Justice System Involvement',
    fieldType: 'dropdown',
    required: false,
    options: [
      'No involvement',
      'Past conviction',
      'Past incarceration',
      'Current parole/probation',
      'Pending charges',
      'Recently released (within 6 months)',
      'Client prefers not to answer',
    ],
    helpText: 'Current or past involvement with criminal justice system',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-003', 'PROG-006'],
    appliesTo: 'individual' as const,
    profiles: [],
    synonyms: [],
    hmisCompliant: false,
    order: 16,
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'CF-017',
    name: 'foster_care_background',
    label: 'Foster Care Background',
    fieldType: 'dropdown',
    required: true,
    options: [
      'Aged out of foster care',
      'Left foster care early (before 18)',
      'Currently in extended foster care',
      'Never in foster care',
    ],
    helpText: 'Foster care history (required for youth programs)',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-006'],
    appliesTo: 'individual' as const,
    profiles: [],
    synonyms: [],
    hmisCompliant: false,
    order: 17,
    createdAt: new Date('2026-03-05'),
    updatedAt: new Date('2026-03-05'),
  },
  {
    id: 'CF-018',
    name: 'desired_job_field',
    label: 'Desired Job Field',
    fieldType: 'dropdown',
    required: false,
    options: [
      'Healthcare',
      'Construction',
      'Hospitality',
      'Retail',
      'Manufacturing',
      'Office/Administrative',
      'Food service',
      'Transportation/Logistics',
      'Technology',
      'Other',
      'Undecided',
    ],
    helpText: 'Preferred career field for training and placement',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-003'],
    appliesTo: 'individual' as const,
    profiles: [],
    synonyms: [],
    hmisCompliant: false,
    order: 18,
    createdAt: new Date('2026-03-10'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: 'CF-019',
    name: 'current_medication',
    label: 'Currently Taking Medication',
    fieldType: 'dropdown',
    required: false,
    options: [
      'Yes - for mental health',
      'Yes - for physical health',
      'Yes - for both',
      'No',
      'Client prefers not to answer',
    ],
    helpText: 'Current medication status (not specific medications)',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-004'],
    appliesTo: 'individual' as const,
    profiles: [],
    synonyms: [],
    hmisCompliant: false,
    order: 19,
    createdAt: new Date('2026-03-12'),
    updatedAt: new Date('2026-03-12'),
  },
  {
    id: 'CF-020',
    name: 'transportation_access',
    label: 'Transportation Access',
    fieldType: 'dropdown',
    required: false,
    options: [
      'Own vehicle',
      'Public transit pass',
      'Access to rides',
      'Walking/biking only',
      'No reliable transportation',
    ],
    helpText: 'How participant accesses transportation',
    visibleInIntake: true,
    visibleInProfile: true,
    programSpecific: true,
    programIds: ['PROG-003', 'PROG-005'],
    appliesTo: 'individual' as const,
    profiles: [],
    synonyms: [],
    hmisCompliant: false,
    order: 20,
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
  },
];
