import { Assessment, AssessmentTemplate, Goal } from '@/types/assessments';

// Assessment Templates
export const mockAssessmentTemplates: AssessmentTemplate[] = [
  {
    id: 'TPL-001',
    name: 'Housing Stability Assessment',
    description: 'Comprehensive assessment of housing stability and barriers',
    assessmentType: 'intake',
    programs: ['PROG-001', 'PROG-002', 'PROG-006'],
    questions: [
      {
        id: 'Q1',
        question: 'Current housing situation?',
        type: 'multiple-choice',
        options: [
          'Emergency shelter',
          'Transitional housing',
          'Staying with friends/family',
          'Street/unsheltered',
          'Other',
        ],
        required: true,
      },
      {
        id: 'Q2',
        question: 'How long have you been without permanent housing?',
        type: 'multiple-choice',
        options: [
          'Less than 1 month',
          '1-3 months',
          '3-6 months',
          '6-12 months',
          'More than 1 year',
        ],
        required: true,
      },
      {
        id: 'Q3',
        question: 'What barriers to housing do you face?',
        type: 'checkbox',
        options: [
          'Poor credit',
          'No rental history',
          'Criminal background',
          'Eviction history',
          'No income',
          'Insufficient income',
          'Pets',
          'Other',
        ],
        required: false,
      },
      {
        id: 'Q4',
        question: 'Do you have income from any source?',
        type: 'yes-no',
        required: true,
      },
      {
        id: 'Q5',
        question: 'If yes, approximate monthly income:',
        type: 'number',
        min: 0,
        required: false,
      },
    ],
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'TPL-002',
    name: 'PHQ-9 Depression Screening',
    description: 'Patient Health Questionnaire for depression screening',
    assessmentType: 'progress',
    programs: ['PROG-004'], // Mental Health Services
    frequencyDays: 30,
    questions: [
      {
        id: 'PHQ1',
        question: 'Little interest or pleasure in doing things',
        type: 'scale',
        min: 0,
        max: 3,
        helpText:
          '0=Not at all, 1=Several days, 2=More than half the days, 3=Nearly every day',
        required: true,
        scoringKey: 'PHQ-9',
        scoringValue: 1,
      },
      {
        id: 'PHQ2',
        question: 'Feeling down, depressed, or hopeless',
        type: 'scale',
        min: 0,
        max: 3,
        required: true,
        scoringKey: 'PHQ-9',
        scoringValue: 1,
      },
      {
        id: 'PHQ3',
        question: 'Trouble falling or staying asleep, or sleeping too much',
        type: 'scale',
        min: 0,
        max: 3,
        required: true,
        scoringKey: 'PHQ-9',
        scoringValue: 1,
      },
      {
        id: 'PHQ4',
        question: 'Feeling tired or having little energy',
        type: 'scale',
        min: 0,
        max: 3,
        required: true,
        scoringKey: 'PHQ-9',
        scoringValue: 1,
      },
      {
        id: 'PHQ5',
        question: 'Poor appetite or overeating',
        type: 'scale',
        min: 0,
        max: 3,
        required: true,
        scoringKey: 'PHQ-9',
        scoringValue: 1,
      },
    ],
    scoringRules: [
      {
        name: 'PHQ-9',
        description: 'Depression severity score',
        calculation: 'sum',
        questionIds: ['PHQ1', 'PHQ2', 'PHQ3', 'PHQ4', 'PHQ5'],
        ranges: [
          {
            min: 0,
            max: 4,
            label: 'Minimal depression',
            severity: 'low',
            recommendation: 'Continue monitoring',
          },
          {
            min: 5,
            max: 9,
            label: 'Mild depression',
            severity: 'low',
            recommendation: 'Consider therapy or support groups',
          },
          {
            min: 10,
            max: 14,
            label: 'Moderate depression',
            severity: 'medium',
            recommendation: 'Therapy and possible medication evaluation',
          },
          {
            min: 15,
            max: 19,
            label: 'Moderately severe depression',
            severity: 'high',
            recommendation: 'Immediate therapy and medication evaluation',
          },
          {
            min: 20,
            max: 27,
            label: 'Severe depression',
            severity: 'critical',
            recommendation: 'Urgent psychiatric evaluation required',
          },
        ],
      },
    ],
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'TPL-003',
    name: 'Employment Readiness Assessment',
    description: 'Assessment of job readiness and barriers to employment',
    assessmentType: 'intake',
    programs: ['PROG-003'], // Job Training
    questions: [
      {
        id: 'EMP1',
        question: 'Current employment status',
        type: 'multiple-choice',
        options: [
          'Employed full-time',
          'Employed part-time',
          'Self-employed',
          'Unemployed',
          'Disabled',
          'Student',
        ],
        required: true,
      },
      {
        id: 'EMP2',
        question: 'Highest education level completed',
        type: 'multiple-choice',
        options: [
          'Less than high school',
          'High school/GED',
          'Some college',
          'Associate degree',
          'Bachelor degree',
          'Graduate degree',
        ],
        required: true,
      },
      {
        id: 'EMP3',
        question: 'Do you have reliable transportation?',
        type: 'yes-no',
        required: true,
      },
      {
        id: 'EMP4',
        question: 'What barriers to employment do you face?',
        type: 'checkbox',
        options: [
          'Lack of skills',
          'Criminal background',
          'No transportation',
          'Health issues',
          'Childcare needs',
          'Other',
        ],
        required: false,
      },
    ],
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'TPL-004',
    name: 'Program Exit Survey',
    description: 'Final assessment completed at program exit',
    assessmentType: 'exit',
    programs: [], // Available to all programs
    questions: [
      {
        id: 'EXIT1',
        question: 'Did you achieve your program goals?',
        type: 'multiple-choice',
        options: [
          'Yes, all goals achieved',
          'Partially achieved',
          'No, goals not achieved',
        ],
        required: true,
      },
      {
        id: 'EXIT2',
        question: 'How would you rate the services you received?',
        type: 'scale',
        min: 1,
        max: 5,
        helpText: '1=Poor, 5=Excellent',
        required: true,
      },
      {
        id: 'EXIT3',
        question: 'Current housing situation',
        type: 'multiple-choice',
        options: [
          'Permanent housing',
          'Transitional housing',
          'Emergency shelter',
          'Staying with friends/family',
          'Unsheltered',
          'Other',
        ],
        required: true,
      },
      {
        id: 'EXIT4',
        question: 'Current employment status',
        type: 'multiple-choice',
        options: [
          'Employed full-time',
          'Employed part-time',
          'Self-employed',
          'Unemployed',
          'Disabled',
          'Student',
          'Other',
        ],
        required: true,
      },
      {
        id: 'EXIT5',
        question: 'What was most helpful about this program?',
        type: 'textarea',
        required: false,
      },
      {
        id: 'EXIT6',
        question: 'What could be improved?',
        type: 'textarea',
        required: false,
      },
    ],
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
];

// Mock Goals
export const mockGoals: Goal[] = [
  // John Smith - ENR-003 (Rapid Rehousing)
  {
    id: 'GOAL-001',
    enrollmentId: 'ENR-003',
    participantId: 'P-001',
    goal: 'Maintain stable housing for 12+ months',
    description:
      'Successfully sustain permanent housing with decreasing rental assistance',
    category: 'housing',
    status: 'in-progress',
    targetDate: new Date('2026-10-01'),
    milestones: [
      {
        id: 'MS-001',
        description: 'Complete first 3 months without issues',
        targetDate: new Date('2026-01-01'),
        completedDate: new Date('2026-01-05'),
        status: 'completed',
        notes: 'Rent paid on time, no lease violations',
      },
      {
        id: 'MS-002',
        description: 'Increase income contribution by 25%',
        targetDate: new Date('2026-04-01'),
        status: 'pending',
      },
    ],
    progressNotes: [
      'Participant maintaining housing well, no issues to date',
      'Employment stable at local cafe',
    ],
    createdBy: 'Sarah Johnson',
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2026-03-29'),
  },
  {
    id: 'GOAL-002',
    enrollmentId: 'ENR-003',
    participantId: 'P-001',
    goal: 'Build emergency savings fund',
    description: 'Save $500 in emergency fund',
    category: 'financial',
    status: 'in-progress',
    targetDate: new Date('2026-06-01'),
    milestones: [
      {
        id: 'MS-003',
        description: 'Save first $100',
        targetDate: new Date('2026-01-01'),
        completedDate: new Date('2026-01-15'),
        status: 'completed',
      },
      {
        id: 'MS-004',
        description: 'Reach $250',
        targetDate: new Date('2026-03-01'),
        status: 'pending',
      },
    ],
    progressNotes: ['Opened savings account', 'Setting aside $50 per paycheck'],
    createdBy: 'Sarah Johnson',
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2026-03-29'),
  },
  // Jane Doe - ENR-005 (Job Training)
  {
    id: 'GOAL-003',
    enrollmentId: 'ENR-005',
    participantId: 'P-002',
    goal: 'Complete IT certification program',
    description: 'Earn CompTIA A+ certification',
    category: 'education',
    status: 'in-progress',
    targetDate: new Date('2026-05-01'),
    milestones: [
      {
        id: 'MS-005',
        description: 'Complete coursework',
        targetDate: new Date('2026-04-15'),
        status: 'pending',
      },
      {
        id: 'MS-006',
        description: 'Pass certification exam',
        targetDate: new Date('2026-05-01'),
        status: 'pending',
      },
    ],
    progressNotes: [
      'Attending classes regularly, 90% attendance',
      'Strong performance on practice tests',
    ],
    createdBy: 'Michael Chen',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'GOAL-004',
    enrollmentId: 'ENR-005',
    participantId: 'P-002',
    goal: 'Secure full-time IT employment',
    description:
      'Obtain full-time position in IT field within 30 days of certification',
    category: 'employment',
    status: 'not-started',
    targetDate: new Date('2026-06-01'),
    milestones: [],
    progressNotes: [],
    createdBy: 'Michael Chen',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  // Michael Johnson - ENR-007 (Mental Health Services)
  {
    id: 'GOAL-005',
    enrollmentId: 'ENR-007',
    participantId: 'P-003',
    goal: 'Medication adherence',
    description: 'Take prescribed medication daily without lapses',
    category: 'health',
    status: 'in-progress',
    targetDate: new Date('2026-07-01'),
    milestones: [
      {
        id: 'MS-007',
        description: '30 consecutive days without missing medication',
        targetDate: new Date('2026-02-20'),
        completedDate: new Date('2026-02-21'),
        status: 'completed',
      },
      {
        id: 'MS-008',
        description: '90 consecutive days without missing medication',
        targetDate: new Date('2026-04-20'),
        status: 'missed',
        notes: 'Missed due to medication lapse in March',
      },
    ],
    progressNotes: [
      'Had crisis due to medication lapse - implementing daily check-ins',
      'Setting up medication reminder system',
    ],
    createdBy: 'Emily Rodriguez',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-03-25'),
  },
  {
    id: 'GOAL-006',
    enrollmentId: 'ENR-007',
    participantId: 'P-003',
    goal: 'Improve daily functioning',
    description:
      'Attend all scheduled therapy sessions and participate in support groups',
    category: 'health',
    status: 'in-progress',
    targetDate: new Date('2026-07-01'),
    milestones: [
      {
        id: 'MS-009',
        description: 'Attend 10 consecutive therapy sessions',
        targetDate: new Date('2026-03-31'),
        completedDate: new Date('2026-03-29'),
        status: 'completed',
      },
      {
        id: 'MS-010',
        description: 'Join and attend support group regularly',
        targetDate: new Date('2026-02-15'),
        completedDate: new Date('2026-02-10'),
        status: 'completed',
      },
    ],
    progressNotes: [
      'Excellent attendance at therapy',
      'Active participant in support group',
      'Building strong peer connections',
    ],
    createdBy: 'Emily Rodriguez',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-03-25'),
  },
  // Maria Garcia - ENR-008 (Educational Support)
  {
    id: 'GOAL-007',
    enrollmentId: 'ENR-008',
    participantId: 'P-004',
    goal: 'Pass GED exam',
    description: 'Successfully pass all sections of the GED examination',
    category: 'education',
    status: 'in-progress',
    targetDate: new Date('2026-05-01'),
    milestones: [
      {
        id: 'MS-011',
        description: 'Complete GED prep coursework',
        targetDate: new Date('2026-04-01'),
        status: 'pending',
      },
      {
        id: 'MS-012',
        description: 'Pass practice GED test',
        targetDate: new Date('2026-04-15'),
        status: 'pending',
      },
      {
        id: 'MS-013',
        description: 'Take official GED exam',
        targetDate: new Date('2026-05-01'),
        status: 'pending',
      },
    ],
    progressNotes: [
      'Making excellent progress in math tutoring',
      'Reading level has improved significantly',
      'Scheduled for exam in late April',
    ],
    createdBy: 'Sarah Johnson',
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'GOAL-008',
    enrollmentId: 'ENR-008',
    participantId: 'P-004',
    goal: 'Enroll in community college',
    description:
      'Apply and enroll in community college program after passing GED',
    category: 'education',
    status: 'not-started',
    targetDate: new Date('2026-09-01'),
    milestones: [],
    progressNotes: ['Waiting for GED completion before proceeding'],
    createdBy: 'Sarah Johnson',
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-02-10'),
  },
];

// Mock Assessments
export const mockAssessments: Assessment[] = [
  // John Smith - Intake assessment for Emergency Shelter (ENR-001)
  {
    id: 'ASM-001',
    enrollmentId: 'ENR-001',
    participantId: 'P-001',
    assessmentType: 'intake',
    templateId: 'TPL-001',
    templateName: 'Housing Stability Assessment',
    assessmentDate: new Date('2025-01-15'),
    completedBy: 'David Williams',
    responses: [
      {
        questionId: 'Q1',
        question: 'Current housing situation?',
        response: 'Street/unsheltered',
      },
      {
        questionId: 'Q2',
        question: 'How long have you been without permanent housing?',
        response: '3-6 months',
      },
      {
        questionId: 'Q3',
        question: 'What barriers to housing do you face?',
        response: ['No income', 'No rental history'],
      },
      {
        questionId: 'Q4',
        question: 'Do you have income from any source?',
        response: false,
      },
    ],
    recommendations: [
      'Immediate emergency shelter placement',
      'Employment assistance referral',
      'Rapid rehousing program evaluation',
    ],
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-15'),
  },
  // Michael Johnson - PHQ-9 assessments showing improvement over time (ENR-007)
  {
    id: 'ASM-002',
    enrollmentId: 'ENR-007',
    participantId: 'P-003',
    assessmentType: 'intake',
    templateId: 'TPL-002',
    templateName: 'PHQ-9 Depression Screening',
    assessmentDate: new Date('2026-01-20'),
    completedBy: 'Emily Rodriguez',
    responses: [
      {
        questionId: 'PHQ1',
        question: 'Little interest or pleasure in doing things',
        response: 3,
      },
      {
        questionId: 'PHQ2',
        question: 'Feeling down, depressed, or hopeless',
        response: 3,
      },
      {
        questionId: 'PHQ3',
        question: 'Trouble falling or staying asleep',
        response: 2,
      },
      {
        questionId: 'PHQ4',
        question: 'Feeling tired or having little energy',
        response: 2,
      },
      {
        questionId: 'PHQ5',
        question: 'Poor appetite or overeating',
        response: 2,
      },
    ],
    scores: { 'PHQ-9': 12 },
    recommendations: [
      'Moderate depression - Therapy and possible medication evaluation',
    ],
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'ASM-003',
    enrollmentId: 'ENR-007',
    participantId: 'P-003',
    assessmentType: 'progress',
    templateId: 'TPL-002',
    templateName: 'PHQ-9 Depression Screening',
    assessmentDate: new Date('2026-02-20'),
    completedBy: 'Emily Rodriguez',
    responses: [
      {
        questionId: 'PHQ1',
        question: 'Little interest or pleasure in doing things',
        response: 2,
      },
      {
        questionId: 'PHQ2',
        question: 'Feeling down, depressed, or hopeless',
        response: 2,
      },
      {
        questionId: 'PHQ3',
        question: 'Trouble falling or staying asleep',
        response: 1,
      },
      {
        questionId: 'PHQ4',
        question: 'Feeling tired or having little energy',
        response: 1,
      },
      {
        questionId: 'PHQ5',
        question: 'Poor appetite or overeating',
        response: 1,
      },
    ],
    scores: { 'PHQ-9': 7 },
    recommendations: ['Mild depression - Consider therapy or support groups'],
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'ASM-004',
    enrollmentId: 'ENR-007',
    participantId: 'P-003',
    assessmentType: 'progress',
    templateId: 'TPL-002',
    templateName: 'PHQ-9 Depression Screening',
    assessmentDate: new Date('2026-03-25'),
    completedBy: 'Emily Rodriguez',
    responses: [
      {
        questionId: 'PHQ1',
        question: 'Little interest or pleasure in doing things',
        response: 3,
      },
      {
        questionId: 'PHQ2',
        question: 'Feeling down, depressed, or hopeless',
        response: 3,
      },
      {
        questionId: 'PHQ3',
        question: 'Trouble falling or staying asleep',
        response: 3,
      },
      {
        questionId: 'PHQ4',
        question: 'Feeling tired or having little energy',
        response: 3,
      },
      {
        questionId: 'PHQ5',
        question: 'Poor appetite or overeating',
        response: 2,
      },
    ],
    scores: { 'PHQ-9': 14 },
    recommendations: [
      'Moderate depression - Therapy and possible medication evaluation',
    ],
    createdAt: new Date('2026-03-25'),
    updatedAt: new Date('2026-03-25'),
  },
  // Jane Doe - Employment readiness (ENR-005)
  {
    id: 'ASM-005',
    enrollmentId: 'ENR-005',
    participantId: 'P-002',
    assessmentType: 'intake',
    templateId: 'TPL-003',
    templateName: 'Employment Readiness Assessment',
    assessmentDate: new Date('2026-02-01'),
    completedBy: 'Michael Chen',
    responses: [
      {
        questionId: 'EMP1',
        question: 'Current employment status',
        response: 'Unemployed',
      },
      {
        questionId: 'EMP2',
        question: 'Highest education level completed',
        response: 'High school/GED',
      },
      {
        questionId: 'EMP3',
        question: 'Do you have reliable transportation?',
        response: true,
      },
      {
        questionId: 'EMP4',
        question: 'What barriers to employment do you face?',
        response: ['Lack of skills'],
      },
    ],
    recommendations: [
      'IT skills training program recommended',
      'Transportation assistance not needed',
      'Job placement services after training completion',
    ],
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
];
