import { ServiceType, ServiceTransaction } from '@/types/services';

// Service Types - Based on SERVICE_LIBRARY but assigned to specific programs
export const mockServiceTypes: ServiceType[] = [
  // Emergency Shelter Services (PROG-001)
  {
    id: 'SVC-TYPE-001',
    name: 'Emergency Shelter',
    description: 'Overnight emergency shelter accommodation',
    category: 'housing',
    unit: 'nights',
    defaultAmount: 1,
    costPerUnit: 35,
    programs: ['PROG-001'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-023',
    name: 'Meals Provided',
    description: 'On-site meal service',
    category: 'food',
    unit: 'meals',
    defaultAmount: 3,
    costPerUnit: 5,
    programs: ['PROG-001'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-029',
    name: 'Follow-up Contact',
    description: 'Regular check-in and support',
    category: 'case-management',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 50,
    programs: ['PROG-001', 'PROG-002', 'PROG-003', 'PROG-004', 'PROG-005'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  // Rapid Rehousing Services (PROG-002)
  {
    id: 'SVC-TYPE-002',
    name: 'Rental Assistance',
    description: 'Financial assistance for rent payments',
    category: 'housing',
    unit: 'dollars',
    defaultAmount: 500,
    costPerUnit: 1,
    programs: ['PROG-002'],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-003',
    name: 'Security Deposit Assistance',
    description: 'One-time assistance for housing security deposits',
    category: 'housing',
    unit: 'dollars',
    defaultAmount: 1000,
    costPerUnit: 1,
    programs: ['PROG-002'],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-005',
    name: 'Housing Search Assistance',
    description: 'Support finding and applying for housing',
    category: 'housing',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 50,
    programs: ['PROG-002'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-019',
    name: 'Financial Literacy Training',
    description: 'Money management and budgeting education',
    category: 'financial',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 50,
    programs: ['PROG-002'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  // Job Training Services (PROG-003)
  {
    id: 'SVC-TYPE-006',
    name: 'Job Counseling',
    description: 'One-on-one employment counseling session',
    category: 'employment',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 75,
    programs: ['PROG-003'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-007',
    name: 'Resume Assistance',
    description: 'Help creating or updating resume',
    category: 'employment',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 50,
    programs: ['PROG-003'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-008',
    name: 'Interview Preparation',
    description: 'Mock interviews and preparation coaching',
    category: 'employment',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 60,
    programs: ['PROG-003'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-010',
    name: 'Vocational Training',
    description: 'Skills training and certification programs',
    category: 'employment',
    unit: 'hours',
    defaultAmount: 40,
    costPerUnit: 25,
    programs: ['PROG-003'],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-025',
    name: 'Transportation Voucher',
    description: 'Bus/transit fare assistance',
    category: 'transportation',
    unit: 'dollars',
    defaultAmount: 20,
    costPerUnit: 1,
    programs: ['PROG-003'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  // Mental Health Services (PROG-004)
  {
    id: 'SVC-TYPE-016',
    name: 'Mental Health Counseling',
    description: 'Individual therapy session',
    category: 'health',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 120,
    programs: ['PROG-004'],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-017',
    name: 'Substance Abuse Treatment',
    description: 'Counseling and treatment for substance use',
    category: 'health',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 100,
    programs: ['PROG-004'],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-018',
    name: 'Medication Assistance',
    description: 'Financial help with prescription medications',
    category: 'health',
    unit: 'dollars',
    defaultAmount: 100,
    costPerUnit: 1,
    programs: ['PROG-004'],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  // Educational Support Services (PROG-005)
  {
    id: 'SVC-TYPE-011',
    name: 'GED Classes',
    description: 'GED preparation classes',
    category: 'education',
    unit: 'hours',
    defaultAmount: 2,
    costPerUnit: 30,
    programs: ['PROG-005'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-013',
    name: 'Tutoring',
    description: 'One-on-one academic tutoring',
    category: 'education',
    unit: 'hours',
    defaultAmount: 1,
    costPerUnit: 40,
    programs: ['PROG-005'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-014',
    name: 'Scholarship Assistance',
    description: 'Help applying for educational scholarships',
    category: 'education',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 50,
    programs: ['PROG-005'],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  // Universal Services (available across multiple programs)
  {
    id: 'SVC-TYPE-027',
    name: 'Intake Assessment',
    description: 'Initial comprehensive needs assessment',
    category: 'case-management',
    unit: 'assessments',
    defaultAmount: 1,
    costPerUnit: 100,
    programs: ['PROG-001', 'PROG-002', 'PROG-003', 'PROG-004', 'PROG-005', 'PROG-006'],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-028',
    name: 'Case Planning',
    description: 'Develop individualized service plan',
    category: 'case-management',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 80,
    programs: ['PROG-001', 'PROG-002', 'PROG-003', 'PROG-004', 'PROG-005', 'PROG-006'],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-030',
    name: 'Progress Review',
    description: 'Formal assessment of goal progress',
    category: 'case-management',
    unit: 'assessments',
    defaultAmount: 1,
    costPerUnit: 90,
    programs: ['PROG-001', 'PROG-002', 'PROG-003', 'PROG-004', 'PROG-005', 'PROG-006'],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
];

// Service Transactions - Realistic service delivery records
export const mockServiceTransactions: ServiceTransaction[] = [
  // John Smith - Emergency Shelter (ENR-001)
  {
    id: 'SVC-TXN-001',
    serviceTypeId: 'SVC-TYPE-001',
    participantId: 'P-001',
    enrollmentId: 'ENR-001',
    providedBy: '4',
    serviceDate: new Date('2025-01-15'),
    quantity: 75,
    unit: 'nights',
    totalCost: 2625,
    outcome: 'successful',
    notes: 'Safe overnight accommodation throughout enrollment',
    location: 'SITE-001',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-03-30'),
  },
  {
    id: 'SVC-TXN-002',
    serviceTypeId: 'SVC-TYPE-023',
    participantId: 'P-001',
    enrollmentId: 'ENR-001',
    providedBy: 'Downtown Emergency Shelter',
    serviceDate: new Date('2025-01-15'),
    quantity: 225,
    unit: 'meals',
    totalCost: 1125,
    outcome: 'successful',
    notes: '3 meals per day for 75 days',
    location: 'SITE-001',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-03-30'),
  },
  {
    id: 'SVC-TXN-003',
    serviceTypeId: 'SVC-TYPE-029',
    participantId: 'P-001',
    enrollmentId: 'ENR-001',
    providedBy: '4',
    serviceDate: new Date('2025-01-20'),
    quantity: 15,
    unit: 'sessions',
    totalCost: 750,
    outcome: 'successful',
    notes: 'Weekly case management meetings',
    location: 'SITE-001',
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-03-30'),
  },
  // John Smith - Rapid Rehousing (ENR-003 - currently active)
  {
    id: 'SVC-TXN-004',
    serviceTypeId: 'SVC-TYPE-027',
    participantId: 'P-001',
    enrollmentId: 'ENR-003',
    providedBy: '1',
    serviceDate: new Date('2025-10-01'),
    quantity: 1,
    unit: 'assessments',
    totalCost: 100,
    outcome: 'successful',
    notes: 'Comprehensive housing needs assessment',
    location: 'SITE-004',
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-10-01'),
  },
  {
    id: 'SVC-TXN-005',
    serviceTypeId: 'SVC-TYPE-003',
    participantId: 'P-001',
    enrollmentId: 'ENR-003',
    providedBy: '1',
    serviceDate: new Date('2025-10-15'),
    quantity: 2000,
    unit: 'dollars',
    totalCost: 2000,
    outcome: 'successful',
    notes: 'Security deposit for new apartment',
    location: 'SITE-004',
    documentationUrl: '/documents/security-deposit-receipt.pdf',
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2025-10-15'),
  },
  {
    id: 'SVC-TXN-006',
    serviceTypeId: 'SVC-TYPE-002',
    participantId: 'P-001',
    enrollmentId: 'ENR-003',
    providedBy: '1',
    serviceDate: new Date('2025-11-01'),
    quantity: 6000,
    unit: 'dollars',
    totalCost: 6000,
    outcome: 'successful',
    notes: 'Rental assistance - 5 months at $1200/month',
    location: 'SITE-004',
    documentationUrl: '/documents/rental-assistance-agreement.pdf',
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2026-03-29'),
  },
  {
    id: 'SVC-TXN-007',
    serviceTypeId: 'SVC-TYPE-019',
    participantId: 'P-001',
    enrollmentId: 'ENR-003',
    providedBy: '1',
    serviceDate: new Date('2025-10-20'),
    quantity: 8,
    unit: 'sessions',
    totalCost: 400,
    outcome: 'successful',
    notes: 'Financial literacy and budgeting sessions',
    location: 'SITE-004',
    createdAt: new Date('2025-10-20'),
    updatedAt: new Date('2026-03-01'),
  },
  // Jane Doe - Job Training (ENR-005 - currently active)
  {
    id: 'SVC-TXN-008',
    serviceTypeId: 'SVC-TYPE-027',
    participantId: 'P-002',
    enrollmentId: 'ENR-005',
    providedBy: '2',
    serviceDate: new Date('2026-02-01'),
    quantity: 1,
    unit: 'assessments',
    totalCost: 100,
    outcome: 'successful',
    notes: 'Skills and employment assessment',
    location: 'SITE-002',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'SVC-TXN-009',
    serviceTypeId: 'SVC-TYPE-010',
    participantId: 'P-002',
    enrollmentId: 'ENR-005',
    providedBy: '2',
    serviceDate: new Date('2026-02-05'),
    quantity: 120,
    unit: 'hours',
    totalCost: 3000,
    outcome: 'pending',
    notes: 'IT certification program - in progress',
    location: 'SITE-002',
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: 'SVC-TXN-010',
    serviceTypeId: 'SVC-TYPE-007',
    participantId: 'P-002',
    enrollmentId: 'ENR-005',
    providedBy: '2',
    serviceDate: new Date('2026-02-10'),
    quantity: 3,
    unit: 'sessions',
    totalCost: 150,
    outcome: 'successful',
    notes: 'Resume writing and optimization',
    location: 'SITE-002',
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'SVC-TXN-011',
    serviceTypeId: 'SVC-TYPE-008',
    participantId: 'P-002',
    enrollmentId: 'ENR-005',
    providedBy: '2',
    serviceDate: new Date('2026-03-01'),
    quantity: 2,
    unit: 'sessions',
    totalCost: 120,
    outcome: 'successful',
    notes: 'Interview preparation and mock interviews',
    location: 'SITE-002',
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: 'SVC-TXN-012',
    serviceTypeId: 'SVC-TYPE-025',
    participantId: 'P-002',
    enrollmentId: 'ENR-005',
    providedBy: '2',
    serviceDate: new Date('2026-02-01'),
    quantity: 400,
    unit: 'dollars',
    totalCost: 400,
    outcome: 'successful',
    notes: 'Transportation vouchers for training and interviews (2 months)',
    location: 'SITE-002',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-03-20'),
  },
  // Michael Johnson - Mental Health Services (ENR-007 - currently active)
  {
    id: 'SVC-TXN-013',
    serviceTypeId: 'SVC-TYPE-027',
    participantId: 'P-003',
    enrollmentId: 'ENR-007',
    providedBy: '3',
    serviceDate: new Date('2026-01-20'),
    quantity: 1,
    unit: 'assessments',
    totalCost: 100,
    outcome: 'successful',
    notes: 'Mental health screening and assessment',
    location: 'SITE-003',
    documentationUrl: '/documents/mh-assessment.pdf',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'SVC-TXN-014',
    serviceTypeId: 'SVC-TYPE-016',
    participantId: 'P-003',
    enrollmentId: 'ENR-007',
    providedBy: 'Dr. Sarah Martinez',
    serviceDate: new Date('2026-01-25'),
    quantity: 20,
    unit: 'sessions',
    totalCost: 2400,
    outcome: 'successful',
    notes: 'Weekly individual therapy sessions',
    location: 'SITE-003',
    documentationUrl: '/documents/therapy-records.pdf',
    createdAt: new Date('2026-01-25'),
    updatedAt: new Date('2026-03-25'),
  },
  {
    id: 'SVC-TXN-015',
    serviceTypeId: 'SVC-TYPE-018',
    participantId: 'P-003',
    enrollmentId: 'ENR-007',
    providedBy: '3',
    serviceDate: new Date('2026-01-20'),
    quantity: 300,
    unit: 'dollars',
    totalCost: 300,
    outcome: 'successful',
    notes: 'Medication assistance for psychiatric medications (3 months)',
    location: 'SITE-003',
    documentationUrl: '/documents/medication-assistance.pdf',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-03-25'),
  },
  // Maria Garcia - Educational Support (ENR-008 - currently active)
  {
    id: 'SVC-TXN-016',
    serviceTypeId: 'SVC-TYPE-027',
    participantId: 'P-004',
    enrollmentId: 'ENR-008',
    providedBy: '1',
    serviceDate: new Date('2026-02-10'),
    quantity: 1,
    unit: 'assessments',
    totalCost: 100,
    outcome: 'successful',
    notes: 'Educational assessment and goal setting',
    location: 'SITE-002',
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'SVC-TXN-017',
    serviceTypeId: 'SVC-TYPE-011',
    participantId: 'P-004',
    enrollmentId: 'ENR-008',
    providedBy: 'Northside Community Center',
    serviceDate: new Date('2026-02-10'),
    quantity: 80,
    unit: 'hours',
    totalCost: 2400,
    outcome: 'pending',
    notes: 'GED preparation course (in progress)',
    location: 'SITE-002',
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-03-28'),
  },
  {
    id: 'SVC-TXN-018',
    serviceTypeId: 'SVC-TYPE-013',
    participantId: 'P-004',
    enrollmentId: 'ENR-008',
    providedBy: 'Lisa Anderson',
    serviceDate: new Date('2026-02-15'),
    quantity: 12,
    unit: 'hours',
    totalCost: 480,
    outcome: 'successful',
    notes: 'One-on-one math tutoring',
    location: 'SITE-002',
    createdAt: new Date('2026-02-15'),
    updatedAt: new Date('2026-03-28'),
  },
];
