import { ServiceType } from '@/types/services';

/**
 * Pre-built service types library organized by category
 * Organizations can use these as templates or add them directly to their catalog
 */

export const SERVICE_LIBRARY: ServiceType[] = [
  // HOUSING SERVICES
  {
    id: 'SVC-TYPE-001',
    name: 'Emergency Shelter',
    description: 'Overnight emergency shelter accommodation',
    category: 'housing',
    unit: 'nights',
    defaultAmount: 1,
    costPerUnit: 35,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-002',
    name: 'Rental Assistance',
    description: 'Financial assistance for rent payments',
    category: 'housing',
    unit: 'dollars',
    defaultAmount: 500,
    costPerUnit: 1,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-003',
    name: 'Security Deposit Assistance',
    description: 'One-time assistance for housing security deposits',
    category: 'housing',
    unit: 'dollars',
    defaultAmount: 1000,
    costPerUnit: 1,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-004',
    name: 'Moving Assistance',
    description: 'Help with moving costs and logistics',
    category: 'housing',
    unit: 'items',
    defaultAmount: 1,
    costPerUnit: 200,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-005',
    name: 'Housing Search Assistance',
    description: 'Support finding and applying for housing',
    category: 'housing',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 50,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  // EMPLOYMENT SERVICES
  {
    id: 'SVC-TYPE-006',
    name: 'Job Counseling',
    description: 'One-on-one employment counseling session',
    category: 'employment',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 75,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-007',
    name: 'Resume Assistance',
    description: 'Help creating or updating resume',
    category: 'employment',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 50,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-008',
    name: 'Interview Preparation',
    description: 'Mock interviews and preparation coaching',
    category: 'employment',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 60,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-009',
    name: 'Job Placement',
    description: 'Successful job placement and follow-up',
    category: 'employment',
    unit: 'referrals',
    defaultAmount: 1,
    costPerUnit: 100,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-010',
    name: 'Vocational Training',
    description: 'Skills training and certification programs',
    category: 'employment',
    unit: 'hours',
    defaultAmount: 40,
    costPerUnit: 25,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  // EDUCATION SERVICES
  {
    id: 'SVC-TYPE-011',
    name: 'GED Classes',
    description: 'GED preparation classes',
    category: 'education',
    unit: 'hours',
    defaultAmount: 2,
    costPerUnit: 30,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-012',
    name: 'ESL Classes',
    description: 'English as a Second Language instruction',
    category: 'education',
    unit: 'hours',
    defaultAmount: 2,
    costPerUnit: 30,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-013',
    name: 'Tutoring',
    description: 'One-on-one academic tutoring',
    category: 'education',
    unit: 'hours',
    defaultAmount: 1,
    costPerUnit: 40,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-014',
    name: 'Scholarship Assistance',
    description: 'Help applying for educational scholarships',
    category: 'education',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 50,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  // HEALTH SERVICES
  {
    id: 'SVC-TYPE-015',
    name: 'Medical Visit',
    description: 'Primary care medical appointment',
    category: 'health',
    unit: 'visits',
    defaultAmount: 1,
    costPerUnit: 150,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-016',
    name: 'Mental Health Counseling',
    description: 'Individual therapy session',
    category: 'health',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 120,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-017',
    name: 'Substance Abuse Treatment',
    description: 'Counseling and treatment for substance use',
    category: 'health',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 100,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-018',
    name: 'Medication Assistance',
    description: 'Financial help with prescription medications',
    category: 'health',
    unit: 'dollars',
    defaultAmount: 100,
    costPerUnit: 1,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  // FINANCIAL SERVICES
  {
    id: 'SVC-TYPE-019',
    name: 'Financial Literacy Training',
    description: 'Money management and budgeting education',
    category: 'financial',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 50,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-020',
    name: 'Budget Counseling',
    description: 'One-on-one budget planning assistance',
    category: 'financial',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 60,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-021',
    name: 'Emergency Financial Assistance',
    description: 'One-time emergency financial aid',
    category: 'financial',
    unit: 'dollars',
    defaultAmount: 250,
    costPerUnit: 1,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-022',
    name: 'Benefits Application Assistance',
    description: 'Help applying for public benefits',
    category: 'financial',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 75,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  // FOOD SERVICES
  {
    id: 'SVC-TYPE-023',
    name: 'Meals Provided',
    description: 'On-site meal service',
    category: 'food',
    unit: 'meals',
    defaultAmount: 1,
    costPerUnit: 5,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-024',
    name: 'Food Pantry',
    description: 'Groceries and food supplies',
    category: 'food',
    unit: 'items',
    defaultAmount: 1,
    costPerUnit: 40,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  // TRANSPORTATION SERVICES
  {
    id: 'SVC-TYPE-025',
    name: 'Transportation Voucher',
    description: 'Bus/transit fare assistance',
    category: 'transportation',
    unit: 'dollars',
    defaultAmount: 20,
    costPerUnit: 1,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-026',
    name: 'Transportation to Services',
    description: 'Direct transport to appointments',
    category: 'transportation',
    unit: 'visits',
    defaultAmount: 1,
    costPerUnit: 15,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  // CASE MANAGEMENT SERVICES
  {
    id: 'SVC-TYPE-027',
    name: 'Intake Assessment',
    description: 'Initial comprehensive needs assessment',
    category: 'case-management',
    unit: 'assessments',
    defaultAmount: 1,
    costPerUnit: 100,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-028',
    name: 'Case Planning',
    description: 'Develop individualized service plan',
    category: 'case-management',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 80,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-029',
    name: 'Follow-up Contact',
    description: 'Regular check-in and support',
    category: 'case-management',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 50,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-030',
    name: 'Progress Review',
    description: 'Formal assessment of goal progress',
    category: 'case-management',
    unit: 'assessments',
    defaultAmount: 1,
    costPerUnit: 90,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  // LEGAL SERVICES
  {
    id: 'SVC-TYPE-031',
    name: 'Legal Consultation',
    description: 'Consultation with legal professional',
    category: 'legal',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 150,
    programs: [],
    requiresDocumentation: true,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'SVC-TYPE-032',
    name: 'Legal Document Assistance',
    description: 'Help with legal paperwork and forms',
    category: 'legal',
    unit: 'sessions',
    defaultAmount: 1,
    costPerUnit: 75,
    programs: [],
    requiresDocumentation: false,
    active: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
];

/**
 * Get service types by category
 */
export function getServicesByCategory(category: string): ServiceType[] {
  return SERVICE_LIBRARY.filter((service) => service.category === category);
}

/**
 * Get a service type by ID
 */
export function getServiceTypeById(id: string): ServiceType | undefined {
  return SERVICE_LIBRARY.find((service) => service.id === id);
}

/**
 * Get service types by category name
 */
export const SERVICE_CATEGORIES_WITH_TYPES = {
  housing: getServicesByCategory('housing'),
  employment: getServicesByCategory('employment'),
  education: getServicesByCategory('education'),
  health: getServicesByCategory('health'),
  financial: getServicesByCategory('financial'),
  legal: getServicesByCategory('legal'),
  transportation: getServicesByCategory('transportation'),
  food: getServicesByCategory('food'),
  'case-management': getServicesByCategory('case-management'),
  other: getServicesByCategory('other'),
};
