import { CustomField, FieldType } from '@/types/customFields';

export interface StandardDemographicField {
  name: string;
  label: string;
  fieldType: FieldType;
  options?: string[];
  helpText: string;
  required: boolean;
  hmisCompliant?: boolean;
  appliesTo: 'individual' | 'household' | 'entity' | 'all';
  profiles: ('hmis' | 'workforce' | 'healthcare' | 'general' | 'custom')[];
}

export interface StandardSource {
  id: string;
  name: string;
  description: string;
  icon: string;
  fields: StandardDemographicField[];
}

export const STANDARD_SOURCES: StandardSource[] = [
  {
    id: 'hmis',
    name: 'HMIS 2024 Data Standards',
    description: 'HUD Homeless Management Information System standard fields for homeless services',
    icon: '🏠',
    fields: [
      {
        name: 'name_data_quality',
        label: 'Name Data Quality',
        fieldType: 'dropdown',
        options: ['Full name reported', 'Partial name reported', 'Client refused', 'Data not collected'],
        helpText: 'HMIS 3.01 - Quality of name information',
        required: true,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'ssn',
        label: 'Social Security Number',
        fieldType: 'text',
        helpText: 'HMIS 3.02 - Social Security Number (encrypted storage required)',
        required: false,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'ssn_data_quality',
        label: 'SSN Data Quality',
        fieldType: 'dropdown',
        options: ['Full SSN reported', 'Approximate or partial SSN reported', 'Client refused', 'Data not collected'],
        helpText: 'HMIS 3.02 - Quality of SSN information',
        required: true,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'race',
        label: 'Race',
        fieldType: 'multi-select',
        options: [
          'American Indian, Alaska Native, or Indigenous',
          'Asian or Asian American',
          'Black, African American, or African',
          'Native Hawaiian or Pacific Islander',
          'White',
          'Client prefers not to answer',
          'Data not collected',
        ],
        helpText: 'HMIS 3.04 - Race (select all that apply)',
        required: true,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'ethnicity',
        label: 'Ethnicity',
        fieldType: 'dropdown',
        options: ['Hispanic/Latina/e/o', 'Non-Hispanic/Non-Latina/e/o', 'Client prefers not to answer', 'Data not collected'],
        helpText: 'HMIS 3.05 - Ethnicity',
        required: true,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'veteran_status',
        label: 'Veteran Status',
        fieldType: 'dropdown',
        options: ['Yes', 'No', "Client doesn't know", 'Client prefers not to answer', 'Data not collected'],
        helpText: 'HMIS 3.07 - U.S. military veteran status',
        required: true,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'disabling_condition',
        label: 'Disabling Condition',
        fieldType: 'dropdown',
        options: ['Yes', 'No', 'Client prefers not to answer', 'Data not collected'],
        helpText: 'HMIS 3.08 - Does the client have a disabling condition?',
        required: true,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'physical_disability',
        label: 'Physical Disability',
        fieldType: 'dropdown',
        options: ['Yes', 'No', 'Client prefers not to answer', 'Data not collected'],
        helpText: 'HMIS 4.05.1 - Physical disability',
        required: false,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'developmental_disability',
        label: 'Developmental Disability',
        fieldType: 'dropdown',
        options: ['Yes', 'No', 'Client prefers not to answer', 'Data not collected'],
        helpText: 'HMIS 4.05.2 - Developmental disability',
        required: false,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'chronic_health_condition',
        label: 'Chronic Health Condition',
        fieldType: 'dropdown',
        options: ['Yes', 'No', 'Client prefers not to answer', 'Data not collected'],
        helpText: 'HMIS 4.05.3 - Chronic health condition',
        required: false,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'hiv_aids',
        label: 'HIV/AIDS',
        fieldType: 'dropdown',
        options: ['Yes', 'No', 'Client prefers not to answer', 'Data not collected'],
        helpText: 'HMIS 4.05.4 - HIV/AIDS',
        required: false,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'mental_health_disorder',
        label: 'Mental Health Disorder',
        fieldType: 'dropdown',
        options: ['Yes', 'No', 'Client prefers not to answer', 'Data not collected'],
        helpText: 'HMIS 4.05.5 - Mental health disorder',
        required: false,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'substance_use_disorder',
        label: 'Substance Use Disorder',
        fieldType: 'dropdown',
        options: ['Yes', 'No', 'Client prefers not to answer', 'Data not collected'],
        helpText: 'HMIS 4.05.6 - Substance use disorder',
        required: false,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'domestic_violence_survivor',
        label: 'Domestic Violence Survivor',
        fieldType: 'dropdown',
        options: ['Yes', 'No', 'Client prefers not to answer', 'Data not collected'],
        helpText: 'HMIS 4.11 - Domestic violence history',
        required: false,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'prior_living_situation',
        label: 'Prior Living Situation',
        fieldType: 'dropdown',
        options: [
          'Place not meant for habitation',
          'Emergency shelter',
          'Safe Haven',
          'Interim housing',
          'Psychiatric hospital or other psychiatric facility',
          'Substance abuse treatment facility or detox center',
          'Hospital or other residential non-psychiatric medical facility',
          'Jail, prison or juvenile detention facility',
          'Transitional housing',
          'Permanent supportive housing',
          'Staying with family',
          'Staying with friends',
          'Rental by client',
          'Owned by client',
          'Hotel or motel paid by client',
          'Foster care home or group home',
          'Residential project or halfway house',
          'Other',
          'Client prefers not to answer',
          'Data not collected',
        ],
        helpText: 'HMIS 3.917 - Where participant lived prior to enrollment',
        required: false,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
      {
        name: 'length_of_stay_prior_living',
        label: 'Length of Stay in Prior Living Situation',
        fieldType: 'dropdown',
        options: [
          'One night or less',
          'Two to six nights',
          'One week or more, but less than one month',
          'One month or more, but less than 90 days',
          '90 days or more, but less than one year',
          'One year or longer',
          'Client prefers not to answer',
          'Data not collected',
        ],
        helpText: 'HMIS 3.917.2 - Length of time in prior living situation',
        required: false,
        hmisCompliant: true,
        appliesTo: 'individual',
        profiles: ['hmis'],
      },
    ],
  },
  {
    id: 'omb',
    name: 'OMB Race & Ethnicity Standards',
    description: 'Office of Management and Budget Statistical Policy Directive 15',
    icon: '🏛️',
    fields: [
      {
        name: 'omb_race',
        label: 'Race (OMB)',
        fieldType: 'multi-select',
        options: [
          'American Indian or Alaska Native',
          'Asian',
          'Black or African American',
          'Native Hawaiian or Other Pacific Islander',
          'White',
        ],
        helpText: 'OMB minimum categories for race (select all that apply)',
        required: false,
        appliesTo: 'individual',
        profiles: ['general'],
      },
      {
        name: 'omb_ethnicity',
        label: 'Ethnicity (OMB)',
        fieldType: 'dropdown',
        options: ['Hispanic or Latino', 'Not Hispanic or Latino'],
        helpText: 'OMB ethnicity categories',
        required: false,
        appliesTo: 'individual',
        profiles: ['general'],
      },
    ],
  },
  {
    id: 'hhs',
    name: 'HHS Common Data Elements',
    description: 'Health and Human Services standardized health and social service fields',
    icon: '🏥',
    fields: [
      {
        name: 'primary_language',
        label: 'Primary Language',
        fieldType: 'dropdown',
        options: [
          'English',
          'Spanish',
          'Chinese (Mandarin)',
          'Chinese (Cantonese)',
          'Tagalog',
          'Vietnamese',
          'Arabic',
          'French',
          'Korean',
          'Russian',
          'German',
          'Haitian Creole',
          'Portuguese',
          'Italian',
          'Polish',
          'Other',
          'Unknown',
        ],
        helpText: 'Primary language spoken by participant',
        required: false,
        appliesTo: 'individual',
        profiles: ['healthcare', 'general'],
      },
      {
        name: 'interpreter_needed',
        label: 'Interpreter Needed',
        fieldType: 'dropdown',
        options: ['Yes', 'No', 'Unknown'],
        helpText: 'Does participant need language interpretation services?',
        required: false,
        appliesTo: 'individual',
        profiles: ['healthcare', 'general'],
      },
      {
        name: 'insurance_type',
        label: 'Health Insurance Type',
        fieldType: 'multi-select',
        options: [
          'Medicaid',
          'Medicare',
          'Private/Commercial',
          'VA Healthcare',
          'Military (TRICARE)',
          'Indian Health Service',
          'Uninsured',
          'Unknown',
        ],
        helpText: 'Current health insurance coverage (select all that apply)',
        required: false,
        appliesTo: 'individual',
        profiles: ['healthcare'],
      },
      {
        name: 'marital_status',
        label: 'Marital Status',
        fieldType: 'dropdown',
        options: [
          'Single, never married',
          'Married or domestic partnership',
          'Widowed',
          'Divorced',
          'Separated',
          'Unknown',
        ],
        helpText: 'Current marital/partnership status',
        required: false,
        appliesTo: 'individual',
        profiles: ['general'],
      },
      {
        name: 'household_size',
        label: 'Household Size',
        fieldType: 'number',
        helpText: 'Number of people in household',
        required: false,
        appliesTo: 'individual',
        profiles: ['general'],
      },
      {
        name: 'pregnant',
        label: 'Currently Pregnant',
        fieldType: 'dropdown',
        options: ['Yes', 'No', 'Prefers not to answer', 'Unknown'],
        helpText: 'Current pregnancy status',
        required: false,
        appliesTo: 'individual',
        profiles: ['healthcare'],
      },
    ],
  },
  {
    id: 'wioa',
    name: 'WIOA Workforce Data',
    description: 'Workforce Innovation and Opportunity Act common performance measures',
    icon: '💼',
    fields: [
      {
        name: 'education_level',
        label: 'Highest Education Level',
        fieldType: 'dropdown',
        options: [
          'No formal education',
          'Grades 1-8',
          'Grades 9-11',
          'High school diploma or equivalent',
          'Some college, no degree',
          'Associate degree',
          "Bachelor's degree",
          'Post-baccalaureate certificate',
          'Master\'s degree',
          'Doctoral degree',
          'Professional degree',
        ],
        helpText: 'Highest level of education completed',
        required: false,
        appliesTo: 'individual',
        profiles: ['workforce'],
      },
      {
        name: 'employment_status',
        label: 'Employment Status',
        fieldType: 'dropdown',
        options: [
          'Employed full-time',
          'Employed part-time',
          'Self-employed',
          'Unemployed, looking for work',
          'Unemployed, not looking for work',
          'Retired',
          'Disabled, unable to work',
          'Student',
          'Homemaker',
        ],
        helpText: 'Current employment status',
        required: false,
        appliesTo: 'individual',
        profiles: ['workforce'],
      },
      {
        name: 'displaced_homemaker',
        label: 'Displaced Homemaker',
        fieldType: 'dropdown',
        options: ['Yes', 'No'],
        helpText: 'Is participant a displaced homemaker?',
        required: false,
        appliesTo: 'individual',
        profiles: ['workforce'],
      },
      {
        name: 'low_income',
        label: 'Low Income Individual',
        fieldType: 'dropdown',
        options: ['Yes', 'No'],
        helpText: 'Does participant meet WIOA low income definition?',
        required: false,
        appliesTo: 'individual',
        profiles: ['workforce'],
      },
      {
        name: 'english_language_learner',
        label: 'English Language Learner',
        fieldType: 'dropdown',
        options: ['Yes', 'No'],
        helpText: 'Is participant an English language learner?',
        required: false,
        appliesTo: 'individual',
        profiles: ['workforce'],
      },
      {
        name: 'basic_skills_deficient',
        label: 'Basic Skills Deficient',
        fieldType: 'dropdown',
        options: ['Yes', 'No'],
        helpText: 'Does participant lack basic academic skills?',
        required: false,
        appliesTo: 'individual',
        profiles: ['workforce'],
      },
    ],
  },
];
